packages:
  - 'vscode-ext/packages/*'
  - 'vscode-ext/packages'
  - 'baml-schema-wasm-node'
  - 'baml-schema-wasm-web'
  - 'nextjs-plugin'
  - 'common'
  - 'playground-common'
  - 'fiddle-frontend'
  - 'codemirror-lang-baml'
