/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: do not edit it. Instead, edit the BAML
// files and re-generate this code.
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code
'use client'

import { BamlClientFinishReasonError, BamlValidationError } from '@boundaryml/baml/errors'
import { useCallback, useMemo, useReducer, useTransition } from 'react'
import * as Actions from './server'
import * as StreamingActions from './server_streaming'
import type {
  ActionKey,
  BamlStreamResponse,
  FinalReturnType,
  HookProps,
  NonStreamingHookResult,
  NonStreamingProps,
  PartialReturnType,
  ServerAction,
  StreamingHookResult,
  StreamingProps,
} from './types'

/**
 * Type guard to check if the hook props are configured for streaming mode.
 *
 * @template TActionKey - The key of the Actions namespace.
 * @param props - The hook props.
 * @returns {boolean} True if the props indicate streaming mode.
 */
function isStreamingProps<TActionKey extends ActionKey>(
  props: HookProps<TActionKey>,
): props is StreamingProps<TActionKey> {
  return props.stream === true
}

function isBamlError(
  error?: Error | BamlValidationError | BamlClientFinishReasonError,
): error is (BamlValidationError | BamlClientFinishReasonError) & { type: string } {
  const errorType = (error as any)?.type
  return errorType === 'BamlValidationError' || errorType === 'BamlClientFinishReasonError'
}

interface HookState<TPartial, TFinal> {
  isSuccess: boolean
  error?: Error | BamlValidationError | BamlClientFinishReasonError
  data?: TFinal
  partialData?: TPartial
}

type HookStateAction<TPartial, TFinal> =
  | { type: 'START_REQUEST' }
  | { type: 'SET_ERROR'; payload: Error | BamlValidationError | BamlClientFinishReasonError }
  | { type: 'SET_PARTIAL'; payload: TPartial }
  | { type: 'SET_FINAL'; payload: TFinal }
  | { type: 'RESET' }

/**
 * Reducer function to manage the hook state transitions.
 *
 * @template TPartial - The type of the partial (streaming) data.
 * @template TFinal - The type of the final (non‑streaming) data.
 * @param state - The current hook state.
 * @param action - The action to apply.
 * @returns The updated state.
 */
function hookReducer<TPartial, TFinal>(
  state: HookState<TPartial, TFinal>,
  action: HookStateAction<TPartial, TFinal>,
): HookState<TPartial, TFinal> {
  switch (action.type) {
    case 'START_REQUEST':
      return {
        ...state,
        isSuccess: false,
        error: undefined,
        data: undefined,
        partialData: undefined,
      }
    case 'SET_ERROR':
      return {
        ...state,
        isSuccess: false,
        error: action.payload,
        data: undefined,
        partialData: undefined,
      }
    case 'SET_PARTIAL':
      return {
        ...state,
        partialData: action.payload,
      }
    case 'SET_FINAL':
      return {
        ...state,
        isSuccess: true,
        data: action.payload,
        partialData: undefined,
      }
    case 'RESET':
      return {
        isSuccess: false,
        error: undefined,
        data: undefined,
        partialData: undefined,
      }
    default:
      return state
  }
}

/**
 * Base hook for executing BAML server actions, supporting both streaming and non‑streaming modes.
 *
 * This hook provides a unified interface for handling loading states, partial updates, errors,
 * and final responses. It is designed to be used directly with any BAML server action.
 *
 * Features:
 * - **Streaming Support:** Real‑time partial updates via `partialData`, progress indicators, and incremental UI updates.
 * - **State Management:** Manages loading state (`isPending`), success/error flags, and final/partial results.
 * - **Error Handling:** Supports type‑safe error handling for BamlValidationError, BamlClientFinishReasonError, and standard errors.
 *
 * @param Action - The server action to invoke.
 * @param props - Configuration props for the hook.
 * @returns An object with the current state and a `mutate` function to trigger the action.
 *
 * @example
 * ```tsx
 * const { data, error, isPending, mutate } = useBamlAction(StreamingActions.TestAws, { stream: true });
 * ```
 */
export function useBamlAction<TActionKey extends ActionKey>(
  action: ServerAction,
  props: StreamingProps<TActionKey>,
): StreamingHookResult<TActionKey>

export function useBamlAction<TActionKey extends ActionKey>(
  action: ServerAction,
  props?: NonStreamingProps<TActionKey>,
): NonStreamingHookResult<TActionKey>

export function useBamlAction<TActionKey extends ActionKey>(
  action: ServerAction,
  props: HookProps<TActionKey> = {},
): StreamingHookResult<TActionKey> | NonStreamingHookResult<TActionKey> {
  const { onFinal, onError, onPartial } = props
  const isStreaming = isStreamingProps(props)
  const [isPending, startTransition] = useTransition()

  const [state, dispatch] = useReducer(hookReducer<PartialReturnType<TActionKey>, FinalReturnType<TActionKey>>, {
    isSuccess: false,
    error: undefined,
    data: undefined,
    partialData: undefined,
  })

  const mutate = useCallback(
    async (...input: Parameters<ServerAction>) => {
      dispatch({ type: 'START_REQUEST' })
      try {
        let response: Awaited<ReturnType<ServerAction>>
        startTransition(async () => {
          response = await action(...input)
          if (isStreaming && response instanceof ReadableStream) {
            const reader = response.getReader()
            const decoder = new TextDecoder()
            try {
              while (true) {
                const { value, done } = await reader.read()
                if (done) break
                if (value) {
                  const chunk = decoder.decode(value, { stream: true }).trim()
                  try {
                    const parsed: BamlStreamResponse<
                      PartialReturnType<TActionKey>,
                      FinalReturnType<TActionKey>
                    > = JSON.parse(chunk)
                    if (parsed.error) {
                      let error: Error | BamlValidationError | BamlClientFinishReasonError = new Error('Unknown error')

                      if (isBamlError(parsed.error)) {
                        if (parsed.error?.type === 'BamlValidationError') {
                          error = new BamlValidationError(
                            parsed.error.prompt,
                            parsed.error.raw_output,
                            parsed.error.message,
                          )
                        } else if (parsed.error.type === 'BamlClientFinishReasonError') {
                          error = new BamlClientFinishReasonError(
                            parsed.error.prompt,
                            parsed.error.raw_output,
                            parsed.error.message,
                          )
                        }
                      } else {
                        error = new Error(parsed.error.message)
                      }
                      throw error
                    }
                    if (parsed.partial !== undefined) {
                      dispatch({ type: 'SET_PARTIAL', payload: parsed.partial })
                      onPartial?.(parsed.partial)
                    }
                    if (parsed.final !== undefined) {
                      dispatch({ type: 'SET_FINAL', payload: parsed.final })
                      onFinal?.(parsed.final)
                      return
                    }
                  } catch (err: unknown) {
                    dispatch({
                      type: 'SET_ERROR',
                      payload: err as Error | BamlValidationError | BamlClientFinishReasonError,
                    })
                    onError?.(err as Error | BamlValidationError | BamlClientFinishReasonError)
                    break
                  }
                }
              }
            } finally {
              reader.releaseLock()
            }
            return
          }
          // Non‑streaming case
          dispatch({ type: 'SET_FINAL', payload: response })
          onFinal?.(response)
        })
        return response
      } catch (error_: unknown) {
        dispatch({ type: 'SET_ERROR', payload: error_ as Error | BamlValidationError | BamlClientFinishReasonError })
        onError?.(error_ as Error | BamlValidationError | BamlClientFinishReasonError)
        throw error_
      }
    },
    [action, isStreaming, onPartial, onFinal, onError],
  )

  const status = useMemo<'idle' | 'pending' | 'success' | 'error'>(() => {
    if (isPending) return 'pending'
    if (state.error) return 'error'
    if (state.isSuccess) return 'success'
    return 'idle'
  }, [isPending, state.error, state.isSuccess])

  const result = {
    data: state.data,
    error: state.error,
    isError: !!state.error,
    isSuccess: state.isSuccess,
    isPending,
    mutate,
    status,
  }

  return {
    ...result,
    partialData: isStreaming ? state.partialData : undefined,
  }
}
/**
 * A specialized hook for the AaaSamOutputFormat BAML function that supports both streaming and non‑streaming responses.
 *
 * **Input Types:**
 *
 * - recipe: string
 *
 *
 * **Return Type:**
 * - **Non‑streaming:** Recipe
 * - **Streaming Partial:** partial_types.Recipe
 * - **Streaming Final:** Recipe
 *
 * **Usage Patterns:**
 * 1. **Non‑streaming (Default)**
 *    - Best for quick responses and simple UI updates.
 * 2. **Streaming**
 *    - Ideal for long‑running operations or real‑time feedback.
 *
 * **Edge Cases:**
 * - Ensure robust error handling via `onError`.
 * - Handle cases where partial data may be incomplete or missing.
 *
 * @example
 * ```tsx
 * // Basic non‑streaming usage:
 * const { data, error, isPending, mutate } = useAaaSamOutputFormat();
 *
 * // Streaming usage:
 * const { data, partialData, isPending, error, mutate } = useAaaSamOutputFormat({
 *   stream: true,
 *   onPartial: (partial) => console.log('Partial update:', partial),
 *   onFinal: (final) => console.log('Final result:', final),
 *   onError: (err) => console.error('Error:', err),
 * });
 * ```
 */
export function useAaaSamOutputFormat(
  props: StreamingProps<'AaaSamOutputFormat'>,
): StreamingHookResult<'AaaSamOutputFormat'>

export function useAaaSamOutputFormat(
  props?: NonStreamingProps<'AaaSamOutputFormat'>,
): NonStreamingHookResult<'AaaSamOutputFormat'>

export function useAaaSamOutputFormat(
  props: HookProps<'AaaSamOutputFormat'> = {},
): StreamingHookResult<'AaaSamOutputFormat'> | NonStreamingHookResult<'AaaSamOutputFormat'> {
  if (props.stream) {
    return useBamlAction(StreamingActions.AaaSamOutputFormat, props)
  }

  return useBamlAction(Actions.AaaSamOutputFormat, props)
}
/**
 * A specialized hook for the AliasThatPointsToRecursiveType BAML function that supports both streaming and non‑streaming responses.
 *
 * **Input Types:**
 *
 * - list: LinkedListAliasNode
 *
 *
 * **Return Type:**
 * - **Non‑streaming:** LinkedListAliasNode
 * - **Streaming Partial:** partial_types.LinkedListAliasNode
 * - **Streaming Final:** LinkedListAliasNode
 *
 * **Usage Patterns:**
 * 1. **Non‑streaming (Default)**
 *    - Best for quick responses and simple UI updates.
 * 2. **Streaming**
 *    - Ideal for long‑running operations or real‑time feedback.
 *
 * **Edge Cases:**
 * - Ensure robust error handling via `onError`.
 * - Handle cases where partial data may be incomplete or missing.
 *
 * @example
 * ```tsx
 * // Basic non‑streaming usage:
 * const { data, error, isPending, mutate } = useAliasThatPointsToRecursiveType();
 *
 * // Streaming usage:
 * const { data, partialData, isPending, error, mutate } = useAliasThatPointsToRecursiveType({
 *   stream: true,
 *   onPartial: (partial) => console.log('Partial update:', partial),
 *   onFinal: (final) => console.log('Final result:', final),
 *   onError: (err) => console.error('Error:', err),
 * });
 * ```
 */
export function useAliasThatPointsToRecursiveType(
  props: StreamingProps<'AliasThatPointsToRecursiveType'>,
): StreamingHookResult<'AliasThatPointsToRecursiveType'>

export function useAliasThatPointsToRecursiveType(
  props?: NonStreamingProps<'AliasThatPointsToRecursiveType'>,
): NonStreamingHookResult<'AliasThatPointsToRecursiveType'>

export function useAliasThatPointsToRecursiveType(
  props: HookProps<'AliasThatPointsToRecursiveType'> = {},
): StreamingHookResult<'AliasThatPointsToRecursiveType'> | NonStreamingHookResult<'AliasThatPointsToRecursiveType'> {
  if (props.stream) {
    return useBamlAction(StreamingActions.AliasThatPointsToRecursiveType, props)
  }

  return useBamlAction(Actions.AliasThatPointsToRecursiveType, props)
}
/**
 * A specialized hook for the AliasWithMultipleAttrs BAML function that supports both streaming and non‑streaming responses.
 *
 * **Input Types:**
 *
 * - money: Checked<number,"gt_ten">
 *
 *
 * **Return Type:**
 * - **Non‑streaming:** Checked<number,"gt_ten">
 * - **Streaming Partial:** Checked<number,"gt_ten">
 * - **Streaming Final:** Checked<number,"gt_ten">
 *
 * **Usage Patterns:**
 * 1. **Non‑streaming (Default)**
 *    - Best for quick responses and simple UI updates.
 * 2. **Streaming**
 *    - Ideal for long‑running operations or real‑time feedback.
 *
 * **Edge Cases:**
 * - Ensure robust error handling via `onError`.
 * - Handle cases where partial data may be incomplete or missing.
 *
 * @example
 * ```tsx
 * // Basic non‑streaming usage:
 * const { data, error, isPending, mutate } = useAliasWithMultipleAttrs();
 *
 * // Streaming usage:
 * const { data, partialData, isPending, error, mutate } = useAliasWithMultipleAttrs({
 *   stream: true,
 *   onPartial: (partial) => console.log('Partial update:', partial),
 *   onFinal: (final) => console.log('Final result:', final),
 *   onError: (err) => console.error('Error:', err),
 * });
 * ```
 */
export function useAliasWithMultipleAttrs(
  props: StreamingProps<'AliasWithMultipleAttrs'>,
): StreamingHookResult<'AliasWithMultipleAttrs'>

export function useAliasWithMultipleAttrs(
  props?: NonStreamingProps<'AliasWithMultipleAttrs'>,
): NonStreamingHookResult<'AliasWithMultipleAttrs'>

export function useAliasWithMultipleAttrs(
  props: HookProps<'AliasWithMultipleAttrs'> = {},
): StreamingHookResult<'AliasWithMultipleAttrs'> | NonStreamingHookResult<'AliasWithMultipleAttrs'> {
  if (props.stream) {
    return useBamlAction(StreamingActions.AliasWithMultipleAttrs, props)
  }

  return useBamlAction(Actions.AliasWithMultipleAttrs, props)
}
/**
 * A specialized hook for the AliasedInputClass BAML function that supports both streaming and non‑streaming responses.
 *
 * **Input Types:**
 *
 * - input: InputClass
 *
 *
 * **Return Type:**
 * - **Non‑streaming:** string
 * - **Streaming Partial:** string
 * - **Streaming Final:** string
 *
 * **Usage Patterns:**
 * 1. **Non‑streaming (Default)**
 *    - Best for quick responses and simple UI updates.
 * 2. **Streaming**
 *    - Ideal for long‑running operations or real‑time feedback.
 *
 * **Edge Cases:**
 * - Ensure robust error handling via `onError`.
 * - Handle cases where partial data may be incomplete or missing.
 *
 * @example
 * ```tsx
 * // Basic non‑streaming usage:
 * const { data, error, isPending, mutate } = useAliasedInputClass();
 *
 * // Streaming usage:
 * const { data, partialData, isPending, error, mutate } = useAliasedInputClass({
 *   stream: true,
 *   onPartial: (partial) => console.log('Partial update:', partial),
 *   onFinal: (final) => console.log('Final result:', final),
 *   onError: (err) => console.error('Error:', err),
 * });
 * ```
 */
export function useAliasedInputClass(
  props: StreamingProps<'AliasedInputClass'>,
): StreamingHookResult<'AliasedInputClass'>

export function useAliasedInputClass(
  props?: NonStreamingProps<'AliasedInputClass'>,
): NonStreamingHookResult<'AliasedInputClass'>

export function useAliasedInputClass(
  props: HookProps<'AliasedInputClass'> = {},
): StreamingHookResult<'AliasedInputClass'> | NonStreamingHookResult<'AliasedInputClass'> {
  if (props.stream) {
    return useBamlAction(StreamingActions.AliasedInputClass, props)
  }

  return useBamlAction(Actions.AliasedInputClass, props)
}
