/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: do not edit it. Instead, edit the BAML
// files and re-generate this code.
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code
'use client'

import { useState } from 'react';
import type { BamlStream } from '@boundaryml/baml';
import * as React from "react";

export interface useLLMBaseOptions<TFinal> {
  /** Called when final data is received */
  onFinal?: (data: TFinal) => void;
  /** Called when an error occurs */
  onError?: (error: Error) => void;
}

export interface useLLMStreamingOptions<TPartial, TFinal>
  extends useLLMBaseOptions<TFinal> {
  /** Called when partial data is received */
  onPartial?: (data: TPartial) => void;
  /** Whether to use streaming mode */
  stream: true;
}

export interface useLLMNonStreamingOptions<TFinal>
  extends useLLMBaseOptions<TFinal> {
  /** Whether to use streaming mode */
  stream?: false;
}

export type useLLMOptions<TPartial, TFinal> =
  | useLLMStreamingOptions<TPartial, TFinal>
  | useLLMNonStreamingOptions<TFinal>;

export type StreamingServerAction<
  TPartial,
  TFinal,
  TParams extends unknown[],
> = (...args: TParams) => Promise<{
  object: ReadableStream<{ partial: TPartial } | { final: TFinal }>;
}>;

export type NonStreamingServerAction<TFinal, TParams extends unknown[]> = (
  ...args: TParams
) => Promise<TFinal>;

interface BaseReturnType<TFinal, TParams extends unknown[]> {
  /** The final result */
  data: TFinal | null;
  /** Any error that occurred */
  error: Error | null;
  /** Whether an error occurred */
  isError: boolean;
  /** Whether the request is loading */
  isLoading: boolean;
  /** Whether the request completed successfully */
  isSuccess: boolean;
  /** The current status of the request */
  status: "idle" | "loading" | "success" | "error";
  /** Function to make the request with the given parameters */
  mutate: (...args: TParams) => Promise<TFinal | null>;
}

export type StreamingReturnType<
  TPartial,
  TFinal,
  TParams extends unknown[],
> = BaseReturnType<TFinal, TParams> & {
  /** The latest partial result from the stream */
  partialData: TPartial | null;
};

export type NonStreamingReturnType<
  TFinal,
  TParams extends unknown[],
> = BaseReturnType<TFinal, TParams> & {
  /** The latest partial result from the stream */
  partialData: never;
};

type useLLMReturn<TPartial, TFinal, TParams extends unknown[], TOptions> =
  TOptions extends useLLMStreamingOptions<TPartial, TFinal>
    ? StreamingReturnType<TPartial, TFinal, TParams>
    : NonStreamingReturnType<TFinal, TParams>;

/**
 * A hook for making BAML function calls, with optional streaming support.
 *
 * @example
 * ```tsx
 * // Non-streaming usage
 * const {
 *   data,
 *   isLoading,
 *   isSuccess,
 *   error,
 *   mutate
 * } = useLLM(extractResume, {
 *   onFinal: (data) => console.log('Final:', data),
 * });
 *
 * // Streaming usage
 * const {
 *   data,
 *   partialData,
 *   isLoading,
 *   isSuccess,
 *   error,
 *   mutate
 * } = useLLM(extractResume, {
 *   stream: true,
 *   onPartial: (data) => console.log('Partial:', data),
 *   onFinal: (data) => console.log('Final:', data),
 * });
 *
 * // Call the function
 * await mutate("Some text to process");
 * ```
 */
export function useLLM<TPartial, TFinal, TParams extends unknown[]>(
  serverAction:
    | StreamingServerAction<TPartial, TFinal, TParams>
    | NonStreamingServerAction<TFinal, TParams>,
  options: useLLMOptions<TPartial, TFinal> = {},
): useLLMReturn<TPartial, TFinal, TParams, typeof options> {
  const { onFinal, onError } = options;
  const onPartial = (options as useLLMStreamingOptions<TPartial, TFinal>)
    .onPartial;
  const isStreaming = options.stream === true;

  const [isLoading, setIsLoading] = React.useState(false);
  const [isSuccess, setIsSuccess] = React.useState(false);
  const [error, setError] = React.useState<Error | null>(null);
  const [data, setData] = React.useState<TFinal | null>(null);
  const [partialData, setPartialData] = React.useState<TPartial | null>(null);

  const mutate = React.useCallback(
    async (...params: TParams): Promise<TFinal | null> => {
      setIsLoading(true);
      setError(null);
      setData(null);
      setPartialData(null);
      setIsSuccess(false);

      try {
        if (isStreaming) {
          const streamingAction = serverAction as StreamingServerAction<
            TPartial,
            TFinal,
            TParams
          >;
          const response = await streamingAction(...params);
          const stream = response.object;
          const reader = stream.getReader();
          let done = false;

          while (!done) {
            const result = await reader.read();
            done = result.done;

            if (!done && result.value) {
              const value = result.value;
              if ("partial" in value) {
                setPartialData(value.partial);
                onPartial?.(value.partial);
              } else if ("final" in value) {
                setData(value.final);
                setIsSuccess(true);
                onFinal?.(value.final);
                return value.final;
              }
            }
          }
          return null;
        }

        const nonStreamingAction = serverAction as NonStreamingServerAction<
          TFinal,
          TParams
        >;
        const response = await nonStreamingAction(...params);
        setData(response);
        setIsSuccess(true);
        onFinal?.(response);
        return response;
      } catch (error_) {
        const error =
          error_ instanceof Error ? error_ : new Error(String(error_));
        setError(error);
        onError?.(error);
        return null;
      } finally {
        setIsLoading(false);
      }
    },
    [serverAction, isStreaming, onPartial, onFinal, onError],
  );

  const status = React.useMemo<"idle" | "loading" | "success" | "error">(() => {
    if (isLoading) return "loading";
    if (error) return "error";
    if (isSuccess) return "success";
    return "idle";
  }, [isLoading, error, isSuccess]);

  const isError = error !== null;

  const result = {
    data,
    error,
    isError,
    isLoading,
    isSuccess,
    mutate,
    status,
  } as const;

  // Return different types based on streaming mode
  if (isStreaming) {
    return {
      ...result,
      partialData,
    } as StreamingReturnType<TPartial, TFinal, TParams>;
  }

  return result as NonStreamingReturnType<TFinal, TParams>;
}
export function useAaaSamOutputFormat(
    props?: useLLMOptions<RecursivePartialNull<Recipe>, Recipe>
): useLLMReturn<
    RecursivePartialNull<Recipe>,
    Recipe,
    [params: {
        recipe: string
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? AaaSamOutputFormatAction : b.AaaSamOutputFormat,
        props
    );
}

export function useAliasThatPointsToRecursiveType(
    props?: useLLMOptions<RecursivePartialNull<LinkedListAliasNode>, LinkedListAliasNode>
): useLLMReturn<
    RecursivePartialNull<LinkedListAliasNode>,
    LinkedListAliasNode,
    [params: {
        list: LinkedListAliasNode
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? AliasThatPointsToRecursiveTypeAction : b.AliasThatPointsToRecursiveType,
        props
    );
}

export function useAliasWithMultipleAttrs(
    props?: useLLMOptions<RecursivePartialNull<Checked<number,"gt_ten">>, Checked<number,"gt_ten">>
): useLLMReturn<
    RecursivePartialNull<Checked<number,"gt_ten">>,
    Checked<number,"gt_ten">,
    [params: {
        money: Checked<number,"gt_ten">
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? AliasWithMultipleAttrsAction : b.AliasWithMultipleAttrs,
        props
    );
}

export function useAliasedInputClass(
    props?: useLLMOptions<RecursivePartialNull<string>, string>
): useLLMReturn<
    RecursivePartialNull<string>,
    string,
    [params: {
        input: InputClass
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? AliasedInputClassAction : b.AliasedInputClass,
        props
    );
}

export function useAliasedInputClass2(
    props?: useLLMOptions<RecursivePartialNull<string>, string>
): useLLMReturn<
    RecursivePartialNull<string>,
    string,
    [params: {
        input: InputClass
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? AliasedInputClass2Action : b.AliasedInputClass2,
        props
    );
}

export function useAliasedInputClassNested(
    props?: useLLMOptions<RecursivePartialNull<string>, string>
): useLLMReturn<
    RecursivePartialNull<string>,
    string,
    [params: {
        input: InputClassNested
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? AliasedInputClassNestedAction : b.AliasedInputClassNested,
        props
    );
}

export function useAliasedInputEnum(
    props?: useLLMOptions<RecursivePartialNull<string>, string>
): useLLMReturn<
    RecursivePartialNull<string>,
    string,
    [params: {
        input: AliasedEnum
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? AliasedInputEnumAction : b.AliasedInputEnum,
        props
    );
}

export function useAliasedInputList(
    props?: useLLMOptions<RecursivePartialNull<string>, string>
): useLLMReturn<
    RecursivePartialNull<string>,
    string,
    [params: {
        input: AliasedEnum[]
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? AliasedInputListAction : b.AliasedInputList,
        props
    );
}

export function useAllowedOptionals(
    props?: useLLMOptions<RecursivePartialNull<OptionalListAndMap>, OptionalListAndMap>
): useLLMReturn<
    RecursivePartialNull<OptionalListAndMap>,
    OptionalListAndMap,
    [params: {
        optionals: OptionalListAndMap
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? AllowedOptionalsAction : b.AllowedOptionals,
        props
    );
}

export function useAudioInput(
    props?: useLLMOptions<RecursivePartialNull<string>, string>
): useLLMReturn<
    RecursivePartialNull<string>,
    string,
    [params: {
        aud: Audio
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? AudioInputAction : b.AudioInput,
        props
    );
}

export function useBuildLinkedList(
    props?: useLLMOptions<RecursivePartialNull<LinkedList>, LinkedList>
): useLLMReturn<
    RecursivePartialNull<LinkedList>,
    LinkedList,
    [params: {
        input: number[]
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? BuildLinkedListAction : b.BuildLinkedList,
        props
    );
}

export function useBuildTree(
    props?: useLLMOptions<RecursivePartialNull<Tree>, Tree>
): useLLMReturn<
    RecursivePartialNull<Tree>,
    Tree,
    [params: {
        input: BinaryNode
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? BuildTreeAction : b.BuildTree,
        props
    );
}

export function useClassThatPointsToRecursiveClassThroughAlias(
    props?: useLLMOptions<RecursivePartialNull<ClassToRecAlias>, ClassToRecAlias>
): useLLMReturn<
    RecursivePartialNull<ClassToRecAlias>,
    ClassToRecAlias,
    [params: {
        cls: ClassToRecAlias
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? ClassThatPointsToRecursiveClassThroughAliasAction : b.ClassThatPointsToRecursiveClassThroughAlias,
        props
    );
}

export function useClassifyDynEnumTwo(
    props?: useLLMOptions<RecursivePartialNull<(string | DynEnumTwo)>, (string | DynEnumTwo)>
): useLLMReturn<
    RecursivePartialNull<(string | DynEnumTwo)>,
    (string | DynEnumTwo),
    [params: {
        input: string
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? ClassifyDynEnumTwoAction : b.ClassifyDynEnumTwo,
        props
    );
}

export function useClassifyMessage(
    props?: useLLMOptions<RecursivePartialNull<Category>, Category>
): useLLMReturn<
    RecursivePartialNull<Category>,
    Category,
    [params: {
        input: string
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? ClassifyMessageAction : b.ClassifyMessage,
        props
    );
}

export function useClassifyMessage2(
    props?: useLLMOptions<RecursivePartialNull<Category>, Category>
): useLLMReturn<
    RecursivePartialNull<Category>,
    Category,
    [params: {
        input: string
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? ClassifyMessage2Action : b.ClassifyMessage2,
        props
    );
}

export function useClassifyMessage3(
    props?: useLLMOptions<RecursivePartialNull<Category>, Category>
): useLLMReturn<
    RecursivePartialNull<Category>,
    Category,
    [params: {
        input: string
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? ClassifyMessage3Action : b.ClassifyMessage3,
        props
    );
}

export function useCompletion(
    props?: useLLMOptions<RecursivePartialNull<string>, string>
): useLLMReturn<
    RecursivePartialNull<string>,
    string,
    [params: {
        prefix: string,
        suffix: string,
        language: string
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? CompletionAction : b.Completion,
        props
    );
}

export function useCustomTask(
    props?: useLLMOptions<RecursivePartialNull<BookOrder | FlightConfirmation | GroceryReceipt>, BookOrder | FlightConfirmation | GroceryReceipt>
): useLLMReturn<
    RecursivePartialNull<BookOrder | FlightConfirmation | GroceryReceipt>,
    BookOrder | FlightConfirmation | GroceryReceipt,
    [params: {
        input: string
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? CustomTaskAction : b.CustomTask,
        props
    );
}

export function useDescribeImage(
    props?: useLLMOptions<RecursivePartialNull<string>, string>
): useLLMReturn<
    RecursivePartialNull<string>,
    string,
    [params: {
        img: Image
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? DescribeImageAction : b.DescribeImage,
        props
    );
}

export function useDescribeImage2(
    props?: useLLMOptions<RecursivePartialNull<string>, string>
): useLLMReturn<
    RecursivePartialNull<string>,
    string,
    [params: {
        classWithImage: ClassWithImage,
        img2: Image
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? DescribeImage2Action : b.DescribeImage2,
        props
    );
}

export function useDescribeImage3(
    props?: useLLMOptions<RecursivePartialNull<string>, string>
): useLLMReturn<
    RecursivePartialNull<string>,
    string,
    [params: {
        classWithImage: ClassWithImage,
        img2: Image
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? DescribeImage3Action : b.DescribeImage3,
        props
    );
}

export function useDescribeImage4(
    props?: useLLMOptions<RecursivePartialNull<string>, string>
): useLLMReturn<
    RecursivePartialNull<string>,
    string,
    [params: {
        classWithImage: ClassWithImage,
        img2: Image
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? DescribeImage4Action : b.DescribeImage4,
        props
    );
}

export function useDifferentiateUnions(
    props?: useLLMOptions<RecursivePartialNull<OriginalA | OriginalB>, OriginalA | OriginalB>
): useLLMReturn<
    RecursivePartialNull<OriginalA | OriginalB>,
    OriginalA | OriginalB,
    [params: {
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? DifferentiateUnionsAction : b.DifferentiateUnions,
        props
    );
}

export function useDummyOutputFunction(
    props?: useLLMOptions<RecursivePartialNull<DummyOutput>, DummyOutput>
): useLLMReturn<
    RecursivePartialNull<DummyOutput>,
    DummyOutput,
    [params: {
        input: string
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? DummyOutputFunctionAction : b.DummyOutputFunction,
        props
    );
}

export function useDynamicFunc(
    props?: useLLMOptions<RecursivePartialNull<DynamicClassTwo>, DynamicClassTwo>
): useLLMReturn<
    RecursivePartialNull<DynamicClassTwo>,
    DynamicClassTwo,
    [params: {
        input: DynamicClassOne
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? DynamicFuncAction : b.DynamicFunc,
        props
    );
}

export function useDynamicInputOutput(
    props?: useLLMOptions<RecursivePartialNull<DynInputOutput>, DynInputOutput>
): useLLMReturn<
    RecursivePartialNull<DynInputOutput>,
    DynInputOutput,
    [params: {
        input: DynInputOutput
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? DynamicInputOutputAction : b.DynamicInputOutput,
        props
    );
}

export function useDynamicListInputOutput(
    props?: useLLMOptions<RecursivePartialNull<DynInputOutput[]>, DynInputOutput[]>
): useLLMReturn<
    RecursivePartialNull<DynInputOutput[]>,
    DynInputOutput[],
    [params: {
        input: DynInputOutput[]
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? DynamicListInputOutputAction : b.DynamicListInputOutput,
        props
    );
}

export function useExpectFailure(
    props?: useLLMOptions<RecursivePartialNull<string>, string>
): useLLMReturn<
    RecursivePartialNull<string>,
    string,
    [params: {
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? ExpectFailureAction : b.ExpectFailure,
        props
    );
}

export function useExtractContactInfo(
    props?: useLLMOptions<RecursivePartialNull<ContactInfo>, ContactInfo>
): useLLMReturn<
    RecursivePartialNull<ContactInfo>,
    ContactInfo,
    [params: {
        document: string
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? ExtractContactInfoAction : b.ExtractContactInfo,
        props
    );
}

export function useExtractHobby(
    props?: useLLMOptions<RecursivePartialNull<(string | Hobby)[]>, (string | Hobby)[]>
): useLLMReturn<
    RecursivePartialNull<(string | Hobby)[]>,
    (string | Hobby)[],
    [params: {
        text: string
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? ExtractHobbyAction : b.ExtractHobby,
        props
    );
}

export function useExtractNames(
    props?: useLLMOptions<RecursivePartialNull<string[]>, string[]>
): useLLMReturn<
    RecursivePartialNull<string[]>,
    string[],
    [params: {
        input: string
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? ExtractNamesAction : b.ExtractNames,
        props
    );
}

export function useExtractPeople(
    props?: useLLMOptions<RecursivePartialNull<Person[]>, Person[]>
): useLLMReturn<
    RecursivePartialNull<Person[]>,
    Person[],
    [params: {
        text: string
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? ExtractPeopleAction : b.ExtractPeople,
        props
    );
}

export function useExtractReceiptInfo(
    props?: useLLMOptions<RecursivePartialNull<ReceiptInfo>, ReceiptInfo>
): useLLMReturn<
    RecursivePartialNull<ReceiptInfo>,
    ReceiptInfo,
    [params: {
        email: string,
        reason: "curiosity" | "personal_finance"
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? ExtractReceiptInfoAction : b.ExtractReceiptInfo,
        props
    );
}

export function useExtractResume(
    props?: useLLMOptions<RecursivePartialNull<Resume>, Resume>
): useLLMReturn<
    RecursivePartialNull<Resume>,
    Resume,
    [params: {
        resume: string,
        img?: Image | null
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? ExtractResumeAction : b.ExtractResume,
        props
    );
}

export function useExtractResume2(
    props?: useLLMOptions<RecursivePartialNull<Resume>, Resume>
): useLLMReturn<
    RecursivePartialNull<Resume>,
    Resume,
    [params: {
        resume: string
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? ExtractResume2Action : b.ExtractResume2,
        props
    );
}

export function useFnClassOptionalOutput(
    props?: useLLMOptions<RecursivePartialNull<ClassOptionalOutput | null>, ClassOptionalOutput | null>
): useLLMReturn<
    RecursivePartialNull<ClassOptionalOutput | null>,
    ClassOptionalOutput | null,
    [params: {
        input: string
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? FnClassOptionalOutputAction : b.FnClassOptionalOutput,
        props
    );
}

export function useFnClassOptionalOutput2(
    props?: useLLMOptions<RecursivePartialNull<ClassOptionalOutput2 | null>, ClassOptionalOutput2 | null>
): useLLMReturn<
    RecursivePartialNull<ClassOptionalOutput2 | null>,
    ClassOptionalOutput2 | null,
    [params: {
        input: string
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? FnClassOptionalOutput2Action : b.FnClassOptionalOutput2,
        props
    );
}

export function useFnEnumListOutput(
    props?: useLLMOptions<RecursivePartialNull<EnumOutput[]>, EnumOutput[]>
): useLLMReturn<
    RecursivePartialNull<EnumOutput[]>,
    EnumOutput[],
    [params: {
        input: string
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? FnEnumListOutputAction : b.FnEnumListOutput,
        props
    );
}

export function useFnEnumOutput(
    props?: useLLMOptions<RecursivePartialNull<EnumOutput>, EnumOutput>
): useLLMReturn<
    RecursivePartialNull<EnumOutput>,
    EnumOutput,
    [params: {
        input: string
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? FnEnumOutputAction : b.FnEnumOutput,
        props
    );
}

export function useFnLiteralClassInputOutput(
    props?: useLLMOptions<RecursivePartialNull<LiteralClassHello>, LiteralClassHello>
): useLLMReturn<
    RecursivePartialNull<LiteralClassHello>,
    LiteralClassHello,
    [params: {
        input: LiteralClassHello
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? FnLiteralClassInputOutputAction : b.FnLiteralClassInputOutput,
        props
    );
}

export function useFnLiteralUnionClassInputOutput(
    props?: useLLMOptions<RecursivePartialNull<LiteralClassOne | LiteralClassTwo>, LiteralClassOne | LiteralClassTwo>
): useLLMReturn<
    RecursivePartialNull<LiteralClassOne | LiteralClassTwo>,
    LiteralClassOne | LiteralClassTwo,
    [params: {
        input: LiteralClassOne | LiteralClassTwo
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? FnLiteralUnionClassInputOutputAction : b.FnLiteralUnionClassInputOutput,
        props
    );
}

export function useFnNamedArgsSingleStringOptional(
    props?: useLLMOptions<RecursivePartialNull<string>, string>
): useLLMReturn<
    RecursivePartialNull<string>,
    string,
    [params: {
        myString?: string | null
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? FnNamedArgsSingleStringOptionalAction : b.FnNamedArgsSingleStringOptional,
        props
    );
}

export function useFnOutputBool(
    props?: useLLMOptions<RecursivePartialNull<boolean>, boolean>
): useLLMReturn<
    RecursivePartialNull<boolean>,
    boolean,
    [params: {
        input: string
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? FnOutputBoolAction : b.FnOutputBool,
        props
    );
}

export function useFnOutputClass(
    props?: useLLMOptions<RecursivePartialNull<TestOutputClass>, TestOutputClass>
): useLLMReturn<
    RecursivePartialNull<TestOutputClass>,
    TestOutputClass,
    [params: {
        input: string
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? FnOutputClassAction : b.FnOutputClass,
        props
    );
}

export function useFnOutputClassList(
    props?: useLLMOptions<RecursivePartialNull<TestOutputClass[]>, TestOutputClass[]>
): useLLMReturn<
    RecursivePartialNull<TestOutputClass[]>,
    TestOutputClass[],
    [params: {
        input: string
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? FnOutputClassListAction : b.FnOutputClassList,
        props
    );
}

export function useFnOutputClassNested(
    props?: useLLMOptions<RecursivePartialNull<TestClassNested>, TestClassNested>
): useLLMReturn<
    RecursivePartialNull<TestClassNested>,
    TestClassNested,
    [params: {
        input: string
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? FnOutputClassNestedAction : b.FnOutputClassNested,
        props
    );
}

export function useFnOutputClassWithEnum(
    props?: useLLMOptions<RecursivePartialNull<TestClassWithEnum>, TestClassWithEnum>
): useLLMReturn<
    RecursivePartialNull<TestClassWithEnum>,
    TestClassWithEnum,
    [params: {
        input: string
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? FnOutputClassWithEnumAction : b.FnOutputClassWithEnum,
        props
    );
}

export function useFnOutputInt(
    props?: useLLMOptions<RecursivePartialNull<number>, number>
): useLLMReturn<
    RecursivePartialNull<number>,
    number,
    [params: {
        input: string
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? FnOutputIntAction : b.FnOutputInt,
        props
    );
}

export function useFnOutputLiteralBool(
    props?: useLLMOptions<RecursivePartialNull<false>, false>
): useLLMReturn<
    RecursivePartialNull<false>,
    false,
    [params: {
        input: string
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? FnOutputLiteralBoolAction : b.FnOutputLiteralBool,
        props
    );
}

export function useFnOutputLiteralInt(
    props?: useLLMOptions<RecursivePartialNull<5>, 5>
): useLLMReturn<
    RecursivePartialNull<5>,
    5,
    [params: {
        input: string
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? FnOutputLiteralIntAction : b.FnOutputLiteralInt,
        props
    );
}

export function useFnOutputLiteralString(
    props?: useLLMOptions<RecursivePartialNull<"example output">, "example output">
): useLLMReturn<
    RecursivePartialNull<"example output">,
    "example output",
    [params: {
        input: string
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? FnOutputLiteralStringAction : b.FnOutputLiteralString,
        props
    );
}

export function useFnOutputStringList(
    props?: useLLMOptions<RecursivePartialNull<string[]>, string[]>
): useLLMReturn<
    RecursivePartialNull<string[]>,
    string[],
    [params: {
        input: string
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? FnOutputStringListAction : b.FnOutputStringList,
        props
    );
}

export function useFnTestAliasedEnumOutput(
    props?: useLLMOptions<RecursivePartialNull<TestEnum>, TestEnum>
): useLLMReturn<
    RecursivePartialNull<TestEnum>,
    TestEnum,
    [params: {
        input: string
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? FnTestAliasedEnumOutputAction : b.FnTestAliasedEnumOutput,
        props
    );
}

export function useFnTestClassAlias(
    props?: useLLMOptions<RecursivePartialNull<TestClassAlias>, TestClassAlias>
): useLLMReturn<
    RecursivePartialNull<TestClassAlias>,
    TestClassAlias,
    [params: {
        input: string
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? FnTestClassAliasAction : b.FnTestClassAlias,
        props
    );
}

export function useFnTestNamedArgsSingleEnum(
    props?: useLLMOptions<RecursivePartialNull<string>, string>
): useLLMReturn<
    RecursivePartialNull<string>,
    string,
    [params: {
        myArg: NamedArgsSingleEnum
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? FnTestNamedArgsSingleEnumAction : b.FnTestNamedArgsSingleEnum,
        props
    );
}

export function useGetDataType(
    props?: useLLMOptions<RecursivePartialNull<RaysData>, RaysData>
): useLLMReturn<
    RecursivePartialNull<RaysData>,
    RaysData,
    [params: {
        text: string
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? GetDataTypeAction : b.GetDataType,
        props
    );
}

export function useGetOrderInfo(
    props?: useLLMOptions<RecursivePartialNull<OrderInfo>, OrderInfo>
): useLLMReturn<
    RecursivePartialNull<OrderInfo>,
    OrderInfo,
    [params: {
        email: Email
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? GetOrderInfoAction : b.GetOrderInfo,
        props
    );
}

export function useGetQuery(
    props?: useLLMOptions<RecursivePartialNull<SearchParams>, SearchParams>
): useLLMReturn<
    RecursivePartialNull<SearchParams>,
    SearchParams,
    [params: {
        query: string
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? GetQueryAction : b.GetQuery,
        props
    );
}

export function useInOutEnumMapKey(
    props?: useLLMOptions<RecursivePartialNull<Partial<Record<MapKey, string>>>, Partial<Record<MapKey, string>>>
): useLLMReturn<
    RecursivePartialNull<Partial<Record<MapKey, string>>>,
    Partial<Record<MapKey, string>>,
    [params: {
        i1: Partial<Record<MapKey, string>>,
        i2: Partial<Record<MapKey, string>>
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? InOutEnumMapKeyAction : b.InOutEnumMapKey,
        props
    );
}

export function useInOutLiteralStringUnionMapKey(
    props?: useLLMOptions<RecursivePartialNull<Partial<Record<"one" | "two" | "three" | "four", string>>>, Partial<Record<"one" | "two" | "three" | "four", string>>>
): useLLMReturn<
    RecursivePartialNull<Partial<Record<"one" | "two" | "three" | "four", string>>>,
    Partial<Record<"one" | "two" | "three" | "four", string>>,
    [params: {
        i1: Partial<Record<"one" | "two" | "three" | "four", string>>,
        i2: Partial<Record<"one" | "two" | "three" | "four", string>>
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? InOutLiteralStringUnionMapKeyAction : b.InOutLiteralStringUnionMapKey,
        props
    );
}

export function useInOutSingleLiteralStringMapKey(
    props?: useLLMOptions<RecursivePartialNull<Partial<Record<"key", string>>>, Partial<Record<"key", string>>>
): useLLMReturn<
    RecursivePartialNull<Partial<Record<"key", string>>>,
    Partial<Record<"key", string>>,
    [params: {
        m: Partial<Record<"key", string>>
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? InOutSingleLiteralStringMapKeyAction : b.InOutSingleLiteralStringMapKey,
        props
    );
}

export function useJsonTypeAliasCycle(
    props?: useLLMOptions<RecursivePartialNull<JsonValue>, JsonValue>
): useLLMReturn<
    RecursivePartialNull<JsonValue>,
    JsonValue,
    [params: {
        input: JsonValue
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? JsonTypeAliasCycleAction : b.JsonTypeAliasCycle,
        props
    );
}

export function useLiteralUnionsTest(
    props?: useLLMOptions<RecursivePartialNull<1 | true | "string output">, 1 | true | "string output">
): useLLMReturn<
    RecursivePartialNull<1 | true | "string output">,
    1 | true | "string output",
    [params: {
        input: string
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? LiteralUnionsTestAction : b.LiteralUnionsTest,
        props
    );
}

export function useMakeBlockConstraint(
    props?: useLLMOptions<RecursivePartialNull<Checked<BlockConstraint,"cross_field">>, Checked<BlockConstraint,"cross_field">>
): useLLMReturn<
    RecursivePartialNull<Checked<BlockConstraint,"cross_field">>,
    Checked<BlockConstraint,"cross_field">,
    [params: {
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? MakeBlockConstraintAction : b.MakeBlockConstraint,
        props
    );
}

export function useMakeNestedBlockConstraint(
    props?: useLLMOptions<RecursivePartialNull<NestedBlockConstraint>, NestedBlockConstraint>
): useLLMReturn<
    RecursivePartialNull<NestedBlockConstraint>,
    NestedBlockConstraint,
    [params: {
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? MakeNestedBlockConstraintAction : b.MakeNestedBlockConstraint,
        props
    );
}

export function useMapAlias(
    props?: useLLMOptions<RecursivePartialNull<Record<string, string[]>>, Record<string, string[]>>
): useLLMReturn<
    RecursivePartialNull<Record<string, string[]>>,
    Record<string, string[]>,
    [params: {
        m: Record<string, string[]>
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? MapAliasAction : b.MapAlias,
        props
    );
}

export function useMergeAliasAttributes(
    props?: useLLMOptions<RecursivePartialNull<MergeAttrs>, MergeAttrs>
): useLLMReturn<
    RecursivePartialNull<MergeAttrs>,
    MergeAttrs,
    [params: {
        money: number
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? MergeAliasAttributesAction : b.MergeAliasAttributes,
        props
    );
}

export function useMyFunc(
    props?: useLLMOptions<RecursivePartialNull<DynamicOutput>, DynamicOutput>
): useLLMReturn<
    RecursivePartialNull<DynamicOutput>,
    DynamicOutput,
    [params: {
        input: string
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? MyFuncAction : b.MyFunc,
        props
    );
}

export function useNestedAlias(
    props?: useLLMOptions<RecursivePartialNull<number | string | boolean | number | string[] | Record<string, string[]>>, number | string | boolean | number | string[] | Record<string, string[]>>
): useLLMReturn<
    RecursivePartialNull<number | string | boolean | number | string[] | Record<string, string[]>>,
    number | string | boolean | number | string[] | Record<string, string[]>,
    [params: {
        c: number | string | boolean | number | string[] | Record<string, string[]>
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? NestedAliasAction : b.NestedAlias,
        props
    );
}

export function useNullLiteralClassHello(
    props?: useLLMOptions<RecursivePartialNull<ClassForNullLiteral>, ClassForNullLiteral>
): useLLMReturn<
    RecursivePartialNull<ClassForNullLiteral>,
    ClassForNullLiteral,
    [params: {
        s: string
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? NullLiteralClassHelloAction : b.NullLiteralClassHello,
        props
    );
}

export function useOptionalTest_Function(
    props?: useLLMOptions<RecursivePartialNull<(OptionalTest_ReturnType | null)[]>, (OptionalTest_ReturnType | null)[]>
): useLLMReturn<
    RecursivePartialNull<(OptionalTest_ReturnType | null)[]>,
    (OptionalTest_ReturnType | null)[],
    [params: {
        input: string
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? OptionalTest_FunctionAction : b.OptionalTest_Function,
        props
    );
}

export function usePredictAge(
    props?: useLLMOptions<RecursivePartialNull<FooAny>, FooAny>
): useLLMReturn<
    RecursivePartialNull<FooAny>,
    FooAny,
    [params: {
        name: string
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? PredictAgeAction : b.PredictAge,
        props
    );
}

export function usePredictAgeBare(
    props?: useLLMOptions<RecursivePartialNull<Checked<number,"too_big">>, Checked<number,"too_big">>
): useLLMReturn<
    RecursivePartialNull<Checked<number,"too_big">>,
    Checked<number,"too_big">,
    [params: {
        inp: string
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? PredictAgeBareAction : b.PredictAgeBare,
        props
    );
}

export function usePrimitiveAlias(
    props?: useLLMOptions<RecursivePartialNull<number | string | boolean | number>, number | string | boolean | number>
): useLLMReturn<
    RecursivePartialNull<number | string | boolean | number>,
    number | string | boolean | number,
    [params: {
        p: number | string | boolean | number
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? PrimitiveAliasAction : b.PrimitiveAlias,
        props
    );
}

export function usePromptTestClaude(
    props?: useLLMOptions<RecursivePartialNull<string>, string>
): useLLMReturn<
    RecursivePartialNull<string>,
    string,
    [params: {
        input: string
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? PromptTestClaudeAction : b.PromptTestClaude,
        props
    );
}

export function usePromptTestClaudeChat(
    props?: useLLMOptions<RecursivePartialNull<string>, string>
): useLLMReturn<
    RecursivePartialNull<string>,
    string,
    [params: {
        input: string
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? PromptTestClaudeChatAction : b.PromptTestClaudeChat,
        props
    );
}

export function usePromptTestClaudeChatNoSystem(
    props?: useLLMOptions<RecursivePartialNull<string>, string>
): useLLMReturn<
    RecursivePartialNull<string>,
    string,
    [params: {
        input: string
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? PromptTestClaudeChatNoSystemAction : b.PromptTestClaudeChatNoSystem,
        props
    );
}

export function usePromptTestOpenAI(
    props?: useLLMOptions<RecursivePartialNull<string>, string>
): useLLMReturn<
    RecursivePartialNull<string>,
    string,
    [params: {
        input: string
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? PromptTestOpenAIAction : b.PromptTestOpenAI,
        props
    );
}

export function usePromptTestOpenAIChat(
    props?: useLLMOptions<RecursivePartialNull<string>, string>
): useLLMReturn<
    RecursivePartialNull<string>,
    string,
    [params: {
        input: string
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? PromptTestOpenAIChatAction : b.PromptTestOpenAIChat,
        props
    );
}

export function usePromptTestOpenAIChatNoSystem(
    props?: useLLMOptions<RecursivePartialNull<string>, string>
): useLLMReturn<
    RecursivePartialNull<string>,
    string,
    [params: {
        input: string
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? PromptTestOpenAIChatNoSystemAction : b.PromptTestOpenAIChatNoSystem,
        props
    );
}

export function usePromptTestStreaming(
    props?: useLLMOptions<RecursivePartialNull<string>, string>
): useLLMReturn<
    RecursivePartialNull<string>,
    string,
    [params: {
        input: string
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? PromptTestStreamingAction : b.PromptTestStreaming,
        props
    );
}

export function useRecursiveAliasCycle(
    props?: useLLMOptions<RecursivePartialNull<RecAliasOne>, RecAliasOne>
): useLLMReturn<
    RecursivePartialNull<RecAliasOne>,
    RecAliasOne,
    [params: {
        input: RecAliasOne
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? RecursiveAliasCycleAction : b.RecursiveAliasCycle,
        props
    );
}

export function useRecursiveClassWithAliasIndirection(
    props?: useLLMOptions<RecursivePartialNull<NodeWithAliasIndirection>, NodeWithAliasIndirection>
): useLLMReturn<
    RecursivePartialNull<NodeWithAliasIndirection>,
    NodeWithAliasIndirection,
    [params: {
        cls: NodeWithAliasIndirection
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? RecursiveClassWithAliasIndirectionAction : b.RecursiveClassWithAliasIndirection,
        props
    );
}

export function useReturnAliasWithMergedAttributes(
    props?: useLLMOptions<RecursivePartialNull<Checked<number,"gt_ten">>, Checked<number,"gt_ten">>
): useLLMReturn<
    RecursivePartialNull<Checked<number,"gt_ten">>,
    Checked<number,"gt_ten">,
    [params: {
        money: Checked<number,"gt_ten">
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? ReturnAliasWithMergedAttributesAction : b.ReturnAliasWithMergedAttributes,
        props
    );
}

export function useReturnFailingAssert(
    props?: useLLMOptions<RecursivePartialNull<number>, number>
): useLLMReturn<
    RecursivePartialNull<number>,
    number,
    [params: {
        inp: number
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? ReturnFailingAssertAction : b.ReturnFailingAssert,
        props
    );
}

export function useReturnMalformedConstraints(
    props?: useLLMOptions<RecursivePartialNull<MalformedConstraints>, MalformedConstraints>
): useLLMReturn<
    RecursivePartialNull<MalformedConstraints>,
    MalformedConstraints,
    [params: {
        a: number
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? ReturnMalformedConstraintsAction : b.ReturnMalformedConstraints,
        props
    );
}

export function useSchemaDescriptions(
    props?: useLLMOptions<RecursivePartialNull<Schema>, Schema>
): useLLMReturn<
    RecursivePartialNull<Schema>,
    Schema,
    [params: {
        input: string
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? SchemaDescriptionsAction : b.SchemaDescriptions,
        props
    );
}

export function useSimpleRecursiveListAlias(
    props?: useLLMOptions<RecursivePartialNull<RecursiveListAlias>, RecursiveListAlias>
): useLLMReturn<
    RecursivePartialNull<RecursiveListAlias>,
    RecursiveListAlias,
    [params: {
        input: RecursiveListAlias
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? SimpleRecursiveListAliasAction : b.SimpleRecursiveListAlias,
        props
    );
}

export function useSimpleRecursiveMapAlias(
    props?: useLLMOptions<RecursivePartialNull<RecursiveMapAlias>, RecursiveMapAlias>
): useLLMReturn<
    RecursivePartialNull<RecursiveMapAlias>,
    RecursiveMapAlias,
    [params: {
        input: RecursiveMapAlias
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? SimpleRecursiveMapAliasAction : b.SimpleRecursiveMapAlias,
        props
    );
}

export function useStreamBigNumbers(
    props?: useLLMOptions<RecursivePartialNull<BigNumbers>, BigNumbers>
): useLLMReturn<
    RecursivePartialNull<BigNumbers>,
    BigNumbers,
    [params: {
        digits: number
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? StreamBigNumbersAction : b.StreamBigNumbers,
        props
    );
}

export function useStreamFailingAssertion(
    props?: useLLMOptions<RecursivePartialNull<TwoStoriesOneTitle>, TwoStoriesOneTitle>
): useLLMReturn<
    RecursivePartialNull<TwoStoriesOneTitle>,
    TwoStoriesOneTitle,
    [params: {
        theme: string,
        length: number
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? StreamFailingAssertionAction : b.StreamFailingAssertion,
        props
    );
}

export function useStreamOneBigNumber(
    props?: useLLMOptions<RecursivePartialNull<number>, number>
): useLLMReturn<
    RecursivePartialNull<number>,
    number,
    [params: {
        digits: number
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? StreamOneBigNumberAction : b.StreamOneBigNumber,
        props
    );
}

export function useStreamUnionIntegers(
    props?: useLLMOptions<RecursivePartialNull<(number | string)[]>, (number | string)[]>
): useLLMReturn<
    RecursivePartialNull<(number | string)[]>,
    (number | string)[],
    [params: {
        digits: number
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? StreamUnionIntegersAction : b.StreamUnionIntegers,
        props
    );
}

export function useStreamingCompoundNumbers(
    props?: useLLMOptions<RecursivePartialNull<CompoundBigNumbers>, CompoundBigNumbers>
): useLLMReturn<
    RecursivePartialNull<CompoundBigNumbers>,
    CompoundBigNumbers,
    [params: {
        digits: number,
        yapping: boolean
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? StreamingCompoundNumbersAction : b.StreamingCompoundNumbers,
        props
    );
}

export function useTestAnthropic(
    props?: useLLMOptions<RecursivePartialNull<string>, string>
): useLLMReturn<
    RecursivePartialNull<string>,
    string,
    [params: {
        input: string
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? TestAnthropicAction : b.TestAnthropic,
        props
    );
}

export function useTestAnthropicShorthand(
    props?: useLLMOptions<RecursivePartialNull<string>, string>
): useLLMReturn<
    RecursivePartialNull<string>,
    string,
    [params: {
        input: string
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? TestAnthropicShorthandAction : b.TestAnthropicShorthand,
        props
    );
}

export function useTestAws(
    props?: useLLMOptions<RecursivePartialNull<string>, string>
): useLLMReturn<
    RecursivePartialNull<string>,
    string,
    [params: {
        input: string
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? TestAwsAction : b.TestAws,
        props
    );
}

export function useTestAwsInvalidAccessKey(
    props?: useLLMOptions<RecursivePartialNull<string>, string>
): useLLMReturn<
    RecursivePartialNull<string>,
    string,
    [params: {
        input: string
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? TestAwsInvalidAccessKeyAction : b.TestAwsInvalidAccessKey,
        props
    );
}

export function useTestAwsInvalidProfile(
    props?: useLLMOptions<RecursivePartialNull<string>, string>
): useLLMReturn<
    RecursivePartialNull<string>,
    string,
    [params: {
        input: string
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? TestAwsInvalidProfileAction : b.TestAwsInvalidProfile,
        props
    );
}

export function useTestAwsInvalidRegion(
    props?: useLLMOptions<RecursivePartialNull<string>, string>
): useLLMReturn<
    RecursivePartialNull<string>,
    string,
    [params: {
        input: string
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? TestAwsInvalidRegionAction : b.TestAwsInvalidRegion,
        props
    );
}

export function useTestAwsInvalidSessionToken(
    props?: useLLMOptions<RecursivePartialNull<string>, string>
): useLLMReturn<
    RecursivePartialNull<string>,
    string,
    [params: {
        input: string
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? TestAwsInvalidSessionTokenAction : b.TestAwsInvalidSessionToken,
        props
    );
}

export function useTestAzure(
    props?: useLLMOptions<RecursivePartialNull<string>, string>
): useLLMReturn<
    RecursivePartialNull<string>,
    string,
    [params: {
        input: string
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? TestAzureAction : b.TestAzure,
        props
    );
}

export function useTestAzureFailure(
    props?: useLLMOptions<RecursivePartialNull<string>, string>
): useLLMReturn<
    RecursivePartialNull<string>,
    string,
    [params: {
        input: string
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? TestAzureFailureAction : b.TestAzureFailure,
        props
    );
}

export function useTestCaching(
    props?: useLLMOptions<RecursivePartialNull<string>, string>
): useLLMReturn<
    RecursivePartialNull<string>,
    string,
    [params: {
        input: string,
        not_cached: string
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? TestCachingAction : b.TestCaching,
        props
    );
}

export function useTestFallbackClient(
    props?: useLLMOptions<RecursivePartialNull<string>, string>
): useLLMReturn<
    RecursivePartialNull<string>,
    string,
    [params: {
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? TestFallbackClientAction : b.TestFallbackClient,
        props
    );
}

export function useTestFallbackToShorthand(
    props?: useLLMOptions<RecursivePartialNull<string>, string>
): useLLMReturn<
    RecursivePartialNull<string>,
    string,
    [params: {
        input: string
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? TestFallbackToShorthandAction : b.TestFallbackToShorthand,
        props
    );
}

export function useTestFnNamedArgsSingleBool(
    props?: useLLMOptions<RecursivePartialNull<string>, string>
): useLLMReturn<
    RecursivePartialNull<string>,
    string,
    [params: {
        myBool: boolean
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? TestFnNamedArgsSingleBoolAction : b.TestFnNamedArgsSingleBool,
        props
    );
}

export function useTestFnNamedArgsSingleClass(
    props?: useLLMOptions<RecursivePartialNull<string>, string>
): useLLMReturn<
    RecursivePartialNull<string>,
    string,
    [params: {
        myArg: NamedArgsSingleClass
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? TestFnNamedArgsSingleClassAction : b.TestFnNamedArgsSingleClass,
        props
    );
}

export function useTestFnNamedArgsSingleEnumList(
    props?: useLLMOptions<RecursivePartialNull<string>, string>
): useLLMReturn<
    RecursivePartialNull<string>,
    string,
    [params: {
        myArg: NamedArgsSingleEnumList[]
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? TestFnNamedArgsSingleEnumListAction : b.TestFnNamedArgsSingleEnumList,
        props
    );
}

export function useTestFnNamedArgsSingleFloat(
    props?: useLLMOptions<RecursivePartialNull<string>, string>
): useLLMReturn<
    RecursivePartialNull<string>,
    string,
    [params: {
        myFloat: number
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? TestFnNamedArgsSingleFloatAction : b.TestFnNamedArgsSingleFloat,
        props
    );
}

export function useTestFnNamedArgsSingleInt(
    props?: useLLMOptions<RecursivePartialNull<string>, string>
): useLLMReturn<
    RecursivePartialNull<string>,
    string,
    [params: {
        myInt: number
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? TestFnNamedArgsSingleIntAction : b.TestFnNamedArgsSingleInt,
        props
    );
}

export function useTestFnNamedArgsSingleMapStringToClass(
    props?: useLLMOptions<RecursivePartialNull<Record<string, StringToClassEntry>>, Record<string, StringToClassEntry>>
): useLLMReturn<
    RecursivePartialNull<Record<string, StringToClassEntry>>,
    Record<string, StringToClassEntry>,
    [params: {
        myMap: Record<string, StringToClassEntry>
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? TestFnNamedArgsSingleMapStringToClassAction : b.TestFnNamedArgsSingleMapStringToClass,
        props
    );
}

export function useTestFnNamedArgsSingleMapStringToMap(
    props?: useLLMOptions<RecursivePartialNull<Record<string, Record<string, string>>>, Record<string, Record<string, string>>>
): useLLMReturn<
    RecursivePartialNull<Record<string, Record<string, string>>>,
    Record<string, Record<string, string>>,
    [params: {
        myMap: Record<string, Record<string, string>>
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? TestFnNamedArgsSingleMapStringToMapAction : b.TestFnNamedArgsSingleMapStringToMap,
        props
    );
}

export function useTestFnNamedArgsSingleMapStringToString(
    props?: useLLMOptions<RecursivePartialNull<Record<string, string>>, Record<string, string>>
): useLLMReturn<
    RecursivePartialNull<Record<string, string>>,
    Record<string, string>,
    [params: {
        myMap: Record<string, string>
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? TestFnNamedArgsSingleMapStringToStringAction : b.TestFnNamedArgsSingleMapStringToString,
        props
    );
}

export function useTestFnNamedArgsSingleString(
    props?: useLLMOptions<RecursivePartialNull<string>, string>
): useLLMReturn<
    RecursivePartialNull<string>,
    string,
    [params: {
        myString: string
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? TestFnNamedArgsSingleStringAction : b.TestFnNamedArgsSingleString,
        props
    );
}

export function useTestFnNamedArgsSingleStringArray(
    props?: useLLMOptions<RecursivePartialNull<string>, string>
): useLLMReturn<
    RecursivePartialNull<string>,
    string,
    [params: {
        myStringArray: string[]
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? TestFnNamedArgsSingleStringArrayAction : b.TestFnNamedArgsSingleStringArray,
        props
    );
}

export function useTestFnNamedArgsSingleStringList(
    props?: useLLMOptions<RecursivePartialNull<string>, string>
): useLLMReturn<
    RecursivePartialNull<string>,
    string,
    [params: {
        myArg: string[]
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? TestFnNamedArgsSingleStringListAction : b.TestFnNamedArgsSingleStringList,
        props
    );
}

export function useTestGemini(
    props?: useLLMOptions<RecursivePartialNull<string>, string>
): useLLMReturn<
    RecursivePartialNull<string>,
    string,
    [params: {
        input: string
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? TestGeminiAction : b.TestGemini,
        props
    );
}

export function useTestImageInput(
    props?: useLLMOptions<RecursivePartialNull<string>, string>
): useLLMReturn<
    RecursivePartialNull<string>,
    string,
    [params: {
        img: Image
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? TestImageInputAction : b.TestImageInput,
        props
    );
}

export function useTestImageInputAnthropic(
    props?: useLLMOptions<RecursivePartialNull<string>, string>
): useLLMReturn<
    RecursivePartialNull<string>,
    string,
    [params: {
        img: Image
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? TestImageInputAnthropicAction : b.TestImageInputAnthropic,
        props
    );
}

export function useTestImageListInput(
    props?: useLLMOptions<RecursivePartialNull<string>, string>
): useLLMReturn<
    RecursivePartialNull<string>,
    string,
    [params: {
        imgs: Image[]
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? TestImageListInputAction : b.TestImageListInput,
        props
    );
}

export function useTestMulticlassNamedArgs(
    props?: useLLMOptions<RecursivePartialNull<string>, string>
): useLLMReturn<
    RecursivePartialNull<string>,
    string,
    [params: {
        myArg: NamedArgsSingleClass,
        myArg2: NamedArgsSingleClass
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? TestMulticlassNamedArgsAction : b.TestMulticlassNamedArgs,
        props
    );
}

export function useTestNamedArgsLiteralBool(
    props?: useLLMOptions<RecursivePartialNull<string>, string>
): useLLMReturn<
    RecursivePartialNull<string>,
    string,
    [params: {
        myBool: true
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? TestNamedArgsLiteralBoolAction : b.TestNamedArgsLiteralBool,
        props
    );
}

export function useTestNamedArgsLiteralInt(
    props?: useLLMOptions<RecursivePartialNull<string>, string>
): useLLMReturn<
    RecursivePartialNull<string>,
    string,
    [params: {
        myInt: 1
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? TestNamedArgsLiteralIntAction : b.TestNamedArgsLiteralInt,
        props
    );
}

export function useTestNamedArgsLiteralString(
    props?: useLLMOptions<RecursivePartialNull<string>, string>
): useLLMReturn<
    RecursivePartialNull<string>,
    string,
    [params: {
        myString: "My String"
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? TestNamedArgsLiteralStringAction : b.TestNamedArgsLiteralString,
        props
    );
}

export function useTestOllama(
    props?: useLLMOptions<RecursivePartialNull<string>, string>
): useLLMReturn<
    RecursivePartialNull<string>,
    string,
    [params: {
        input: string
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? TestOllamaAction : b.TestOllama,
        props
    );
}

export function useTestOpenAILegacyProvider(
    props?: useLLMOptions<RecursivePartialNull<string>, string>
): useLLMReturn<
    RecursivePartialNull<string>,
    string,
    [params: {
        input: string
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? TestOpenAILegacyProviderAction : b.TestOpenAILegacyProvider,
        props
    );
}

export function useTestOpenAIShorthand(
    props?: useLLMOptions<RecursivePartialNull<string>, string>
): useLLMReturn<
    RecursivePartialNull<string>,
    string,
    [params: {
        input: string
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? TestOpenAIShorthandAction : b.TestOpenAIShorthand,
        props
    );
}

export function useTestRetryConstant(
    props?: useLLMOptions<RecursivePartialNull<string>, string>
): useLLMReturn<
    RecursivePartialNull<string>,
    string,
    [params: {
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? TestRetryConstantAction : b.TestRetryConstant,
        props
    );
}

export function useTestRetryExponential(
    props?: useLLMOptions<RecursivePartialNull<string>, string>
): useLLMReturn<
    RecursivePartialNull<string>,
    string,
    [params: {
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? TestRetryExponentialAction : b.TestRetryExponential,
        props
    );
}

export function useTestSingleFallbackClient(
    props?: useLLMOptions<RecursivePartialNull<string>, string>
): useLLMReturn<
    RecursivePartialNull<string>,
    string,
    [params: {
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? TestSingleFallbackClientAction : b.TestSingleFallbackClient,
        props
    );
}

export function useTestVertex(
    props?: useLLMOptions<RecursivePartialNull<string>, string>
): useLLMReturn<
    RecursivePartialNull<string>,
    string,
    [params: {
        input: string
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? TestVertexAction : b.TestVertex,
        props
    );
}

export function useTestVertexWithSystemInstructions(
    props?: useLLMOptions<RecursivePartialNull<string>, string>
): useLLMReturn<
    RecursivePartialNull<string>,
    string,
    [params: {
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? TestVertexWithSystemInstructionsAction : b.TestVertexWithSystemInstructions,
        props
    );
}

export function useUnionTest_Function(
    props?: useLLMOptions<RecursivePartialNull<UnionTest_ReturnType>, UnionTest_ReturnType>
): useLLMReturn<
    RecursivePartialNull<UnionTest_ReturnType>,
    UnionTest_ReturnType,
    [params: {
        input: string | boolean
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? UnionTest_FunctionAction : b.UnionTest_Function,
        props
    );
}

export function useUseBlockConstraint(
    props?: useLLMOptions<RecursivePartialNull<number>, number>
): useLLMReturn<
    RecursivePartialNull<number>,
    number,
    [params: {
        inp: BlockConstraintForParam
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? UseBlockConstraintAction : b.UseBlockConstraint,
        props
    );
}

export function useUseMalformedConstraints(
    props?: useLLMOptions<RecursivePartialNull<number>, number>
): useLLMReturn<
    RecursivePartialNull<number>,
    number,
    [params: {
        a: MalformedConstraints2
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? UseMalformedConstraintsAction : b.UseMalformedConstraints,
        props
    );
}

export function useUseNestedBlockConstraint(
    props?: useLLMOptions<RecursivePartialNull<number>, number>
): useLLMReturn<
    RecursivePartialNull<number>,
    number,
    [params: {
        inp: NestedBlockConstraintForParam
    }],
    typeof props
> {
    return useLLM(
        props?.stream ? UseNestedBlockConstraintAction : b.UseNestedBlockConstraint,
        props
    );
}
