/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: do not edit it. Instead, edit the BAML
// files and re-generate this code.
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code
'use server'

import type { Audio, Image } from '@boundaryml/baml'
import { b } from '../index'
import type { Check, Checked } from '../types'

import type {
  AliasedEnum,
  AnotherObject,
  BigNumbers,
  BinaryNode,
  Blah,
  BlockConstraint,
  BlockConstraintForParam,
  BookOrder,
  Category,
  Category2,
  Category3,
  ClassForNullLiteral,
  ClassOptionalOutput,
  ClassOptionalOutput2,
  ClassToRecAlias,
  ClassWithBlockDone,
  ClassWithImage,
  ClassWithoutDone,
  Color,
  ComplexMemoryObject,
  CompoundBigNumbers,
  ContactInfo,
  CustomTaskResult,
  DataType,
  DummyOutput,
  DynEnumOne,
  DynEnumTwo,
  DynInputOutput,
  DynamicClassOne,
  DynamicClassTwo,
  DynamicOutput,
  Earthling,
  Education,
  Email,
  EmailAddress,
  EnumInClass,
  EnumOutput,
  Event,
  FakeImage,
  FlightConfirmation,
  FooAny,
  Forest,
  FormatterTest0,
  FormatterTest1,
  FormatterTest2,
  FormatterTest3,
  GroceryReceipt,
  Hobby,
  InnerClass,
  InnerClass2,
  InputClass,
  InputClassNested,
  JsonArray,
  JsonEntry,
  JsonObject,
  JsonTemplate,
  JsonValue,
  LinkedList,
  LinkedListAliasNode,
  LiteralClassHello,
  LiteralClassOne,
  LiteralClassTwo,
  MalformedConstraints,
  MalformedConstraints2,
  MapKey,
  Martian,
  MemoryObject,
  MergeAttrs,
  NamedArgsSingleClass,
  NamedArgsSingleEnum,
  NamedArgsSingleEnumList,
  Nested,
  Nested2,
  NestedBlockConstraint,
  NestedBlockConstraintForParam,
  Node,
  NodeWithAliasIndirection,
  OptionalListAndMap,
  OptionalTest_CategoryType,
  OptionalTest_Prop1,
  OptionalTest_ReturnType,
  OrderInfo,
  OrderStatus,
  OriginalA,
  OriginalB,
  Person,
  PhoneNumber,
  Quantity,
  RaysData,
  RecAliasOne,
  RecAliasThree,
  RecAliasTwo,
  ReceiptInfo,
  ReceiptItem,
  Recipe,
  RecursiveAliasDependency,
  RecursiveListAlias,
  RecursiveMapAlias,
  Resume,
  Schema,
  SearchParams,
  SemanticContainer,
  SimpleTag,
  SmallThing,
  SomeClassNestedDynamic,
  StringToClassEntry,
  Tag,
  TestClassAlias,
  TestClassNested,
  TestClassWithEnum,
  TestEnum,
  TestMemoryOutput,
  TestOutputClass,
  Tree,
  TwoStoriesOneTitle,
  UnionTest_ReturnType,
  UniverseQuestion,
  UniverseQuestionInput,
  WithReasoning,
} from '../types'

import type * as types from '../types'

/**
 * Streaming BAML server actions that return ReadableStreams.
 */

/**
 * Executes the streaming variant of the "AaaSamOutputFormat" BAML action.
 *
 * This action initiates a streaming response by calling the corresponding
 * BAML stream function. The returned stream yields incremental updates.
 *
 * @param { string } recipe - Input parameter.
 *
 * @returns {ReadableStream<Uint8Array>} A stream that yields incremental updates from the action.
 */
export const AaaSamOutputFormat = async (recipe: string): Promise<ReadableStream<Uint8Array>> => {
  const stream = b.stream.AaaSamOutputFormat(recipe)
  return Promise.resolve(stream.toStreamable())
}

/**
 * Executes the streaming variant of the "AliasThatPointsToRecursiveType" BAML action.
 *
 * This action initiates a streaming response by calling the corresponding
 * BAML stream function. The returned stream yields incremental updates.
 *
 * @param { LinkedListAliasNode } list - Input parameter.
 *
 * @returns {ReadableStream<Uint8Array>} A stream that yields incremental updates from the action.
 */
export const AliasThatPointsToRecursiveType = async (
  list: LinkedListAliasNode,
): Promise<ReadableStream<Uint8Array>> => {
  const stream = b.stream.AliasThatPointsToRecursiveType(list)
  return Promise.resolve(stream.toStreamable())
}

/**
 * Executes the streaming variant of the "AliasWithMultipleAttrs" BAML action.
 *
 * This action initiates a streaming response by calling the corresponding
 * BAML stream function. The returned stream yields incremental updates.
 *
 * @param { Checked<number,"gt_ten"> } money - Input parameter.
 *
 * @returns {ReadableStream<Uint8Array>} A stream that yields incremental updates from the action.
 */
export const AliasWithMultipleAttrs = async (money: Checked<number, 'gt_ten'>): Promise<ReadableStream<Uint8Array>> => {
  const stream = b.stream.AliasWithMultipleAttrs(money)
  return Promise.resolve(stream.toStreamable())
}

/**
 * Executes the streaming variant of the "AliasedInputClass" BAML action.
 *
 * This action initiates a streaming response by calling the corresponding
 * BAML stream function. The returned stream yields incremental updates.
 *
 * @param { InputClass } input - Input parameter.
 *
 * @returns {ReadableStream<Uint8Array>} A stream that yields incremental updates from the action.
 */
export const AliasedInputClass = async (input: InputClass): Promise<ReadableStream<Uint8Array>> => {
  const stream = b.stream.AliasedInputClass(input)
  return Promise.resolve(stream.toStreamable())
}

/**
 * Executes the streaming variant of the "AliasedInputClass2" BAML action.
 *
 * This action initiates a streaming response by calling the corresponding
 * BAML stream function. The returned stream yields incremental updates.
 *
 * @param { InputClass } input - Input parameter.
 *
 * @returns {ReadableStream<Uint8Array>} A stream that yields incremental updates from the action.
 */
export const AliasedInputClass2 = async (input: InputClass): Promise<ReadableStream<Uint8Array>> => {
  const stream = b.stream.AliasedInputClass2(input)
  return Promise.resolve(stream.toStreamable())
}

/**
 * Executes the streaming variant of the "AliasedInputClassNested" BAML action.
 *
 * This action initiates a streaming response by calling the corresponding
 * BAML stream function. The returned stream yields incremental updates.
 *
 * @param { InputClassNested } input - Input parameter.
 *
 * @returns {ReadableStream<Uint8Array>} A stream that yields incremental updates from the action.
 */
export const AliasedInputClassNested = async (input: InputClassNested): Promise<ReadableStream<Uint8Array>> => {
  const stream = b.stream.AliasedInputClassNested(input)
  return Promise.resolve(stream.toStreamable())
}

/**
 * Executes the streaming variant of the "AliasedInputEnum" BAML action.
 *
 * This action initiates a streaming response by calling the corresponding
 * BAML stream function. The returned stream yields incremental updates.
 *
 * @param { AliasedEnum } input - Input parameter.
 *
 * @returns {ReadableStream<Uint8Array>} A stream that yields incremental updates from the action.
 */
export const AliasedInputEnum = async (input: AliasedEnum): Promise<ReadableStream<Uint8Array>> => {
  const stream = b.stream.AliasedInputEnum(input)
  return Promise.resolve(stream.toStreamable())
}

/**
 * Executes the streaming variant of the "AliasedInputList" BAML action.
 *
 * This action initiates a streaming response by calling the corresponding
 * BAML stream function. The returned stream yields incremental updates.
 *
 * @param { AliasedEnum[] } input - Input parameter.
 *
 * @returns {ReadableStream<Uint8Array>} A stream that yields incremental updates from the action.
 */
export const AliasedInputList = async (input: AliasedEnum[]): Promise<ReadableStream<Uint8Array>> => {
  const stream = b.stream.AliasedInputList(input)
  return Promise.resolve(stream.toStreamable())
}

/**
 * Executes the streaming variant of the "AllowedOptionals" BAML action.
 *
 * This action initiates a streaming response by calling the corresponding
 * BAML stream function. The returned stream yields incremental updates.
 *
 * @param { OptionalListAndMap } optionals - Input parameter.
 *
 * @returns {ReadableStream<Uint8Array>} A stream that yields incremental updates from the action.
 */
export const AllowedOptionals = async (optionals: OptionalListAndMap): Promise<ReadableStream<Uint8Array>> => {
  const stream = b.stream.AllowedOptionals(optionals)
  return Promise.resolve(stream.toStreamable())
}

/**
 * Executes the streaming variant of the "AssertFn" BAML action.
 *
 * This action initiates a streaming response by calling the corresponding
 * BAML stream function. The returned stream yields incremental updates.
 *
 * @param { number } a - Input parameter.
 *
 * @returns {ReadableStream<Uint8Array>} A stream that yields incremental updates from the action.
 */
export const AssertFn = async (a: number): Promise<ReadableStream<Uint8Array>> => {
  const stream = b.stream.AssertFn(a)
  return Promise.resolve(stream.toStreamable())
}

/**
 * Executes the streaming variant of the "AudioInput" BAML action.
 *
 * This action initiates a streaming response by calling the corresponding
 * BAML stream function. The returned stream yields incremental updates.
 *
 * @param { Audio } aud - Input parameter.
 *
 * @returns {ReadableStream<Uint8Array>} A stream that yields incremental updates from the action.
 */
export const AudioInput = async (aud: Audio): Promise<ReadableStream<Uint8Array>> => {
  const stream = b.stream.AudioInput(aud)
  return Promise.resolve(stream.toStreamable())
}

/**
 * Executes the streaming variant of the "BuildLinkedList" BAML action.
 *
 * This action initiates a streaming response by calling the corresponding
 * BAML stream function. The returned stream yields incremental updates.
 *
 * @param { number[] } input - Input parameter.
 *
 * @returns {ReadableStream<Uint8Array>} A stream that yields incremental updates from the action.
 */
export const BuildLinkedList = async (input: number[]): Promise<ReadableStream<Uint8Array>> => {
  const stream = b.stream.BuildLinkedList(input)
  return Promise.resolve(stream.toStreamable())
}

/**
 * Executes the streaming variant of the "BuildTree" BAML action.
 *
 * This action initiates a streaming response by calling the corresponding
 * BAML stream function. The returned stream yields incremental updates.
 *
 * @param { BinaryNode } input - Input parameter.
 *
 * @returns {ReadableStream<Uint8Array>} A stream that yields incremental updates from the action.
 */
export const BuildTree = async (input: BinaryNode): Promise<ReadableStream<Uint8Array>> => {
  const stream = b.stream.BuildTree(input)
  return Promise.resolve(stream.toStreamable())
}

/**
 * Executes the streaming variant of the "ClassThatPointsToRecursiveClassThroughAlias" BAML action.
 *
 * This action initiates a streaming response by calling the corresponding
 * BAML stream function. The returned stream yields incremental updates.
 *
 * @param { ClassToRecAlias } cls - Input parameter.
 *
 * @returns {ReadableStream<Uint8Array>} A stream that yields incremental updates from the action.
 */
export const ClassThatPointsToRecursiveClassThroughAlias = async (
  cls: ClassToRecAlias,
): Promise<ReadableStream<Uint8Array>> => {
  const stream = b.stream.ClassThatPointsToRecursiveClassThroughAlias(cls)
  return Promise.resolve(stream.toStreamable())
}

/**
 * Executes the streaming variant of the "ClassifyDynEnumTwo" BAML action.
 *
 * This action initiates a streaming response by calling the corresponding
 * BAML stream function. The returned stream yields incremental updates.
 *
 * @param { string } input - Input parameter.
 *
 * @returns {ReadableStream<Uint8Array>} A stream that yields incremental updates from the action.
 */
export const ClassifyDynEnumTwo = async (input: string): Promise<ReadableStream<Uint8Array>> => {
  const stream = b.stream.ClassifyDynEnumTwo(input)
  return Promise.resolve(stream.toStreamable())
}
