/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: do not edit it. Instead, edit the BAML
// files and re-generate this code.
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code
'use server'

import type { Audio, Image } from '@boundaryml/baml'
import { b } from '../index'
import type { Check, Checked } from '../types'

import type {
  AliasedEnum,
  AnotherObject,
  BigNumbers,
  BinaryNode,
  Blah,
  BlockConstraint,
  BlockConstraintForParam,
  BookOrder,
  Category,
  Category2,
  Category3,
  ClassForNullLiteral,
  ClassOptionalOutput,
  ClassOptionalOutput2,
  ClassToRecAlias,
  ClassWithBlockDone,
  ClassWithImage,
  ClassWithoutDone,
  Color,
  ComplexMemoryObject,
  CompoundBigNumbers,
  ContactInfo,
  CustomTaskResult,
  DataType,
  DummyOutput,
  DynEnumOne,
  DynEnumTwo,
  DynInputOutput,
  DynamicClassOne,
  DynamicClassTwo,
  DynamicOutput,
  Earthling,
  Education,
  Email,
  EmailAddress,
  EnumInClass,
  EnumOutput,
  Event,
  FakeImage,
  FlightConfirmation,
  FooAny,
  Forest,
  FormatterTest0,
  FormatterTest1,
  FormatterTest2,
  FormatterTest3,
  GroceryReceipt,
  Hobby,
  InnerClass,
  InnerClass2,
  InputClass,
  InputClassNested,
  JsonArray,
  JsonEntry,
  JsonObject,
  JsonTemplate,
  JsonValue,
  LinkedList,
  LinkedListAliasNode,
  LiteralClassHello,
  LiteralClassOne,
  LiteralClassTwo,
  MalformedConstraints,
  MalformedConstraints2,
  MapKey,
  Martian,
  MemoryObject,
  MergeAttrs,
  NamedArgsSingleClass,
  NamedArgsSingleEnum,
  NamedArgsSingleEnumList,
  Nested,
  Nested2,
  NestedBlockConstraint,
  NestedBlockConstraintForParam,
  Node,
  NodeWithAliasIndirection,
  OptionalListAndMap,
  OptionalTest_CategoryType,
  OptionalTest_Prop1,
  OptionalTest_ReturnType,
  OrderInfo,
  OrderStatus,
  OriginalA,
  OriginalB,
  Person,
  PhoneNumber,
  Quantity,
  RaysData,
  RecAliasOne,
  RecAliasThree,
  RecAliasTwo,
  ReceiptInfo,
  ReceiptItem,
  Recipe,
  RecursiveAliasDependency,
  RecursiveListAlias,
  RecursiveMapAlias,
  Resume,
  Schema,
  SearchParams,
  SemanticContainer,
  SimpleTag,
  SmallThing,
  SomeClassNestedDynamic,
  StringToClassEntry,
  Tag,
  TestClassAlias,
  TestClassNested,
  TestClassWithEnum,
  TestEnum,
  TestMemoryOutput,
  TestOutputClass,
  Tree,
  TwoStoriesOneTitle,
  UnionTest_ReturnType,
  UniverseQuestion,
  UniverseQuestionInput,
  WithReasoning,
} from '../types'

import type * as types from '../types'

/**
 * Regular BAML server actions that return direct responses.
 */

/**
 * Executes the "AaaSamOutputFormat" BAML action.
 *
 * This server action calls the underlying BAML function "AaaSamOutputFormat"
 * with the specified parameters.
 *
 * @param { string } recipe - Input parameter.
 *
 * @returns {Promise<Recipe>} A promise that resolves with the result of the action.
 */
export const AaaSamOutputFormat = async (recipe: string): Promise<Recipe> => {
  return b.AaaSamOutputFormat(recipe)
}

/**
 * Executes the "AliasThatPointsToRecursiveType" BAML action.
 *
 * This server action calls the underlying BAML function "AliasThatPointsToRecursiveType"
 * with the specified parameters.
 *
 * @param { LinkedListAliasNode } list - Input parameter.
 *
 * @returns {Promise<LinkedListAliasNode>} A promise that resolves with the result of the action.
 */
export const AliasThatPointsToRecursiveType = async (list: LinkedListAliasNode): Promise<LinkedListAliasNode> => {
  return b.AliasThatPointsToRecursiveType(list)
}

/**
 * Executes the "AliasWithMultipleAttrs" BAML action.
 *
 * This server action calls the underlying BAML function "AliasWithMultipleAttrs"
 * with the specified parameters.
 *
 * @param { Checked<number,"gt_ten"> } money - Input parameter.
 *
 * @returns {Promise<Checked<number,"gt_ten">>} A promise that resolves with the result of the action.
 */
export const AliasWithMultipleAttrs = async (money: Checked<number, 'gt_ten'>): Promise<Checked<number, 'gt_ten'>> => {
  return b.AliasWithMultipleAttrs(money)
}

/**
 * Executes the "AliasedInputClass" BAML action.
 *
 * This server action calls the underlying BAML function "AliasedInputClass"
 * with the specified parameters.
 *
 * @param { InputClass } input - Input parameter.
 *
 * @returns {Promise<string>} A promise that resolves with the result of the action.
 */
export const AliasedInputClass = async (input: InputClass): Promise<string> => {
  return b.AliasedInputClass(input)
}

/**
 * Executes the "AliasedInputClass2" BAML action.
 *
 * This server action calls the underlying BAML function "AliasedInputClass2"
 * with the specified parameters.
 *
 * @param { InputClass } input - Input parameter.
 *
 * @returns {Promise<string>} A promise that resolves with the result of the action.
 */
export const AliasedInputClass2 = async (input: InputClass): Promise<string> => {
  return b.AliasedInputClass2(input)
}

/**
 * Executes the "AliasedInputClassNested" BAML action.
 *
 * This server action calls the underlying BAML function "AliasedInputClassNested"
 * with the specified parameters.
 *
 * @param { InputClassNested } input - Input parameter.
 *
 * @returns {Promise<string>} A promise that resolves with the result of the action.
 */
export const AliasedInputClassNested = async (input: InputClassNested): Promise<string> => {
  return b.AliasedInputClassNested(input)
}

/**
 * Executes the "AliasedInputEnum" BAML action.
 *
 * This server action calls the underlying BAML function "AliasedInputEnum"
 * with the specified parameters.
 *
 * @param { AliasedEnum } input - Input parameter.
 *
 * @returns {Promise<string>} A promise that resolves with the result of the action.
 */
export const AliasedInputEnum = async (input: AliasedEnum): Promise<string> => {
  return b.AliasedInputEnum(input)
}

/**
 * Executes the "AliasedInputList" BAML action.
 *
 * This server action calls the underlying BAML function "AliasedInputList"
 * with the specified parameters.
 *
 * @param { AliasedEnum[] } input - Input parameter.
 *
 * @returns {Promise<string>} A promise that resolves with the result of the action.
 */
export const AliasedInputList = async (input: AliasedEnum[]): Promise<string> => {
  return b.AliasedInputList(input)
}

/**
 * Executes the "AllowedOptionals" BAML action.
 *
 * This server action calls the underlying BAML function "AllowedOptionals"
 * with the specified parameters.
 *
 * @param { OptionalListAndMap } optionals - Input parameter.
 *
 * @returns {Promise<OptionalListAndMap>} A promise that resolves with the result of the action.
 */
export const AllowedOptionals = async (optionals: OptionalListAndMap): Promise<OptionalListAndMap> => {
  return b.AllowedOptionals(optionals)
}

/**
 * Executes the "AssertFn" BAML action.
 *
 * This server action calls the underlying BAML function "AssertFn"
 * with the specified parameters.
 *
 * @param { number } a - Input parameter.
 *
 * @returns {Promise<number>} A promise that resolves with the result of the action.
 */
export const AssertFn = async (a: number): Promise<number> => {
  return b.AssertFn(a)
}

/**
 * Executes the "AudioInput" BAML action.
 *
 * This server action calls the underlying BAML function "AudioInput"
 * with the specified parameters.
 *
 * @param { Audio } aud - Input parameter.
 *
 * @returns {Promise<string>} A promise that resolves with the result of the action.
 */
export const AudioInput = async (aud: Audio): Promise<string> => {
  return b.AudioInput(aud)
}
