/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: do not edit it. Instead, edit the BAML
// files and re-generate this code.
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code
'use server'

import { b } from '../index';
import type { BamlStream } from '@boundaryml/baml';


/**
 * Interface defining the structure of a streamable value with methods
 * to update, complete, and handle errors in the stream.
 */
interface StreamableValue<T> {
  done: (finalValue?: T) => void;
  error: (error: Error) => void;
  object: ReadableStream<T>;
  update: (value: T) => void;
}

/**
 * Creates a streamable value with methods to control the stream
 */
function createStreamableValue<T extends object>(): StreamableValue<T> {
  let controller: ReadableStreamDefaultController<T>;
  const stream = new ReadableStream<T>({
    start(c) {
      controller = c;
    },
  });

  return {
    done: (finalValue?: T) => {
      if (finalValue) {
        controller.enqueue(finalValue);
      }
      controller.close();
    },
    error: (error: Error) => {
      controller.error(error);
    },
    object: stream,
    update: (value: T) => {
      controller.enqueue(value);
    },
  };
}

/**
 * Type alias for defining a StreamableValue based on a BamlStream.
 * It captures either a partial or final result depending on the stream state.
 */
type StreamResult<TStream extends BamlStream<unknown, unknown>> =
  | {
      partial: TStream extends BamlStream<infer PartialResult, unknown>
        ? PartialResult
        : never;
    }
  | {
      final: TStream extends BamlStream<unknown, infer FinalResult>
        ? FinalResult
        : never;
    };

/**
 * Helper function to manage and handle a BamlStream.
 */
async function streamHelper<TStream extends BamlStream<unknown, unknown>>(
  bamlStream: TStream,
): Promise<{
  object: ReadableStream<StreamResult<TStream>>;
}> {
  const stream = createStreamableValue<StreamResult<TStream>>();

  (async () => {
    try {
      for await (const event of bamlStream) {
        stream.update({
          partial: event as TStream extends BamlStream<infer P, unknown>
            ? P
            : never,
        });
      }

      const response = await bamlStream.getFinalResponse();
      stream.update({
        final: response as TStream extends BamlStream<unknown, infer F>
          ? F
          : never,
      });
      stream.done();
    } catch (error) {
      stream.error(error instanceof Error ? error : new Error(String(error)));
    }
  })();

  return { object: stream.object };
}

export type BamlStreamFunction<TPartial, TFinal, TArgs extends unknown[]> = (
  // this: typeof b.stream,
  ...args: TArgs
) => BamlStream<TPartial, TFinal>;

export type MakeStreamableResult<TPartial, TFinal, TArgs extends unknown[]> = (
  ...args: TArgs
) => Promise<{
  object: ReadableStream<{ partial: TPartial } | { final: TFinal }>;
}>;

/**
 * Converts a BAML stream function into a streamable server action.
 */
export function makeStreamable<TPartial, TFinal, TArgs extends unknown[]>(
  streamFunction: BamlStreamFunction<TPartial, TFinal, TArgs>,
): MakeStreamableResult<TPartial, TFinal, TArgs> {
  return async (...args) => {
    const boundFunction = streamFunction.bind(b.stream);
    const stream = boundFunction(...args);
    return streamHelper(stream);
  };
}
export const AaaSamOutputFormatAction = makeStreamable(b.stream.AaaSamOutputFormat);

export const AliasThatPointsToRecursiveTypeAction = makeStreamable(b.stream.AliasThatPointsToRecursiveType);

export const AliasWithMultipleAttrsAction = makeStreamable(b.stream.AliasWithMultipleAttrs);

export const AliasedInputClassAction = makeStreamable(b.stream.AliasedInputClass);

export const AliasedInputClass2Action = makeStreamable(b.stream.AliasedInputClass2);

export const AliasedInputClassNestedAction = makeStreamable(b.stream.AliasedInputClassNested);

export const AliasedInputEnumAction = makeStreamable(b.stream.AliasedInputEnum);

export const AliasedInputListAction = makeStreamable(b.stream.AliasedInputList);

export const AllowedOptionalsAction = makeStreamable(b.stream.AllowedOptionals);

export const AudioInputAction = makeStreamable(b.stream.AudioInput);

export const BuildLinkedListAction = makeStreamable(b.stream.BuildLinkedList);

export const BuildTreeAction = makeStreamable(b.stream.BuildTree);

export const ClassThatPointsToRecursiveClassThroughAliasAction = makeStreamable(b.stream.ClassThatPointsToRecursiveClassThroughAlias);

export const ClassifyDynEnumTwoAction = makeStreamable(b.stream.ClassifyDynEnumTwo);

export const ClassifyMessageAction = makeStreamable(b.stream.ClassifyMessage);

export const ClassifyMessage2Action = makeStreamable(b.stream.ClassifyMessage2);

export const ClassifyMessage3Action = makeStreamable(b.stream.ClassifyMessage3);

export const CompletionAction = makeStreamable(b.stream.Completion);

export const CustomTaskAction = makeStreamable(b.stream.CustomTask);

export const DescribeImageAction = makeStreamable(b.stream.DescribeImage);

export const DescribeImage2Action = makeStreamable(b.stream.DescribeImage2);

export const DescribeImage3Action = makeStreamable(b.stream.DescribeImage3);

export const DescribeImage4Action = makeStreamable(b.stream.DescribeImage4);

export const DifferentiateUnionsAction = makeStreamable(b.stream.DifferentiateUnions);

export const DummyOutputFunctionAction = makeStreamable(b.stream.DummyOutputFunction);

export const DynamicFuncAction = makeStreamable(b.stream.DynamicFunc);

export const DynamicInputOutputAction = makeStreamable(b.stream.DynamicInputOutput);

export const DynamicListInputOutputAction = makeStreamable(b.stream.DynamicListInputOutput);

export const ExpectFailureAction = makeStreamable(b.stream.ExpectFailure);

export const ExtractContactInfoAction = makeStreamable(b.stream.ExtractContactInfo);

export const ExtractHobbyAction = makeStreamable(b.stream.ExtractHobby);

export const ExtractNamesAction = makeStreamable(b.stream.ExtractNames);

export const ExtractPeopleAction = makeStreamable(b.stream.ExtractPeople);

export const ExtractReceiptInfoAction = makeStreamable(b.stream.ExtractReceiptInfo);

export const ExtractResumeAction = makeStreamable(b.stream.ExtractResume);

export const ExtractResume2Action = makeStreamable(b.stream.ExtractResume2);

export const FnClassOptionalOutputAction = makeStreamable(b.stream.FnClassOptionalOutput);

export const FnClassOptionalOutput2Action = makeStreamable(b.stream.FnClassOptionalOutput2);

export const FnEnumListOutputAction = makeStreamable(b.stream.FnEnumListOutput);

export const FnEnumOutputAction = makeStreamable(b.stream.FnEnumOutput);

export const FnLiteralClassInputOutputAction = makeStreamable(b.stream.FnLiteralClassInputOutput);

export const FnLiteralUnionClassInputOutputAction = makeStreamable(b.stream.FnLiteralUnionClassInputOutput);

export const FnNamedArgsSingleStringOptionalAction = makeStreamable(b.stream.FnNamedArgsSingleStringOptional);

export const FnOutputBoolAction = makeStreamable(b.stream.FnOutputBool);

export const FnOutputClassAction = makeStreamable(b.stream.FnOutputClass);

export const FnOutputClassListAction = makeStreamable(b.stream.FnOutputClassList);

export const FnOutputClassNestedAction = makeStreamable(b.stream.FnOutputClassNested);

export const FnOutputClassWithEnumAction = makeStreamable(b.stream.FnOutputClassWithEnum);

export const FnOutputIntAction = makeStreamable(b.stream.FnOutputInt);

export const FnOutputLiteralBoolAction = makeStreamable(b.stream.FnOutputLiteralBool);

export const FnOutputLiteralIntAction = makeStreamable(b.stream.FnOutputLiteralInt);

export const FnOutputLiteralStringAction = makeStreamable(b.stream.FnOutputLiteralString);

export const FnOutputStringListAction = makeStreamable(b.stream.FnOutputStringList);

export const FnTestAliasedEnumOutputAction = makeStreamable(b.stream.FnTestAliasedEnumOutput);

export const FnTestClassAliasAction = makeStreamable(b.stream.FnTestClassAlias);

export const FnTestNamedArgsSingleEnumAction = makeStreamable(b.stream.FnTestNamedArgsSingleEnum);

export const GetDataTypeAction = makeStreamable(b.stream.GetDataType);

export const GetOrderInfoAction = makeStreamable(b.stream.GetOrderInfo);

export const GetQueryAction = makeStreamable(b.stream.GetQuery);

export const InOutEnumMapKeyAction = makeStreamable(b.stream.InOutEnumMapKey);

export const InOutLiteralStringUnionMapKeyAction = makeStreamable(b.stream.InOutLiteralStringUnionMapKey);

export const InOutSingleLiteralStringMapKeyAction = makeStreamable(b.stream.InOutSingleLiteralStringMapKey);

export const JsonTypeAliasCycleAction = makeStreamable(b.stream.JsonTypeAliasCycle);

export const LiteralUnionsTestAction = makeStreamable(b.stream.LiteralUnionsTest);

export const MakeBlockConstraintAction = makeStreamable(b.stream.MakeBlockConstraint);

export const MakeNestedBlockConstraintAction = makeStreamable(b.stream.MakeNestedBlockConstraint);

export const MapAliasAction = makeStreamable(b.stream.MapAlias);

export const MergeAliasAttributesAction = makeStreamable(b.stream.MergeAliasAttributes);

export const MyFuncAction = makeStreamable(b.stream.MyFunc);

export const NestedAliasAction = makeStreamable(b.stream.NestedAlias);

export const NullLiteralClassHelloAction = makeStreamable(b.stream.NullLiteralClassHello);

export const OptionalTest_FunctionAction = makeStreamable(b.stream.OptionalTest_Function);

export const PredictAgeAction = makeStreamable(b.stream.PredictAge);

export const PredictAgeBareAction = makeStreamable(b.stream.PredictAgeBare);

export const PrimitiveAliasAction = makeStreamable(b.stream.PrimitiveAlias);

export const PromptTestClaudeAction = makeStreamable(b.stream.PromptTestClaude);

export const PromptTestClaudeChatAction = makeStreamable(b.stream.PromptTestClaudeChat);

export const PromptTestClaudeChatNoSystemAction = makeStreamable(b.stream.PromptTestClaudeChatNoSystem);

export const PromptTestOpenAIAction = makeStreamable(b.stream.PromptTestOpenAI);

export const PromptTestOpenAIChatAction = makeStreamable(b.stream.PromptTestOpenAIChat);

export const PromptTestOpenAIChatNoSystemAction = makeStreamable(b.stream.PromptTestOpenAIChatNoSystem);

export const PromptTestStreamingAction = makeStreamable(b.stream.PromptTestStreaming);

export const RecursiveAliasCycleAction = makeStreamable(b.stream.RecursiveAliasCycle);

export const RecursiveClassWithAliasIndirectionAction = makeStreamable(b.stream.RecursiveClassWithAliasIndirection);

export const ReturnAliasWithMergedAttributesAction = makeStreamable(b.stream.ReturnAliasWithMergedAttributes);

export const ReturnFailingAssertAction = makeStreamable(b.stream.ReturnFailingAssert);

export const ReturnMalformedConstraintsAction = makeStreamable(b.stream.ReturnMalformedConstraints);

export const SchemaDescriptionsAction = makeStreamable(b.stream.SchemaDescriptions);

export const SimpleRecursiveListAliasAction = makeStreamable(b.stream.SimpleRecursiveListAlias);

export const SimpleRecursiveMapAliasAction = makeStreamable(b.stream.SimpleRecursiveMapAlias);

export const StreamBigNumbersAction = makeStreamable(b.stream.StreamBigNumbers);

export const StreamFailingAssertionAction = makeStreamable(b.stream.StreamFailingAssertion);

export const StreamOneBigNumberAction = makeStreamable(b.stream.StreamOneBigNumber);

export const StreamUnionIntegersAction = makeStreamable(b.stream.StreamUnionIntegers);

export const StreamingCompoundNumbersAction = makeStreamable(b.stream.StreamingCompoundNumbers);

export const TestAnthropicAction = makeStreamable(b.stream.TestAnthropic);

export const TestAnthropicShorthandAction = makeStreamable(b.stream.TestAnthropicShorthand);

export const TestAwsAction = makeStreamable(b.stream.TestAws);

export const TestAwsInvalidAccessKeyAction = makeStreamable(b.stream.TestAwsInvalidAccessKey);

export const TestAwsInvalidProfileAction = makeStreamable(b.stream.TestAwsInvalidProfile);

export const TestAwsInvalidRegionAction = makeStreamable(b.stream.TestAwsInvalidRegion);

export const TestAwsInvalidSessionTokenAction = makeStreamable(b.stream.TestAwsInvalidSessionToken);

export const TestAzureAction = makeStreamable(b.stream.TestAzure);

export const TestAzureFailureAction = makeStreamable(b.stream.TestAzureFailure);

export const TestCachingAction = makeStreamable(b.stream.TestCaching);

export const TestFallbackClientAction = makeStreamable(b.stream.TestFallbackClient);

export const TestFallbackToShorthandAction = makeStreamable(b.stream.TestFallbackToShorthand);

export const TestFnNamedArgsSingleBoolAction = makeStreamable(b.stream.TestFnNamedArgsSingleBool);

export const TestFnNamedArgsSingleClassAction = makeStreamable(b.stream.TestFnNamedArgsSingleClass);

export const TestFnNamedArgsSingleEnumListAction = makeStreamable(b.stream.TestFnNamedArgsSingleEnumList);

export const TestFnNamedArgsSingleFloatAction = makeStreamable(b.stream.TestFnNamedArgsSingleFloat);

export const TestFnNamedArgsSingleIntAction = makeStreamable(b.stream.TestFnNamedArgsSingleInt);

export const TestFnNamedArgsSingleMapStringToClassAction = makeStreamable(b.stream.TestFnNamedArgsSingleMapStringToClass);

export const TestFnNamedArgsSingleMapStringToMapAction = makeStreamable(b.stream.TestFnNamedArgsSingleMapStringToMap);

export const TestFnNamedArgsSingleMapStringToStringAction = makeStreamable(b.stream.TestFnNamedArgsSingleMapStringToString);

export const TestFnNamedArgsSingleStringAction = makeStreamable(b.stream.TestFnNamedArgsSingleString);

export const TestFnNamedArgsSingleStringArrayAction = makeStreamable(b.stream.TestFnNamedArgsSingleStringArray);

export const TestFnNamedArgsSingleStringListAction = makeStreamable(b.stream.TestFnNamedArgsSingleStringList);

export const TestGeminiAction = makeStreamable(b.stream.TestGemini);

export const TestImageInputAction = makeStreamable(b.stream.TestImageInput);

export const TestImageInputAnthropicAction = makeStreamable(b.stream.TestImageInputAnthropic);

export const TestImageListInputAction = makeStreamable(b.stream.TestImageListInput);

export const TestMulticlassNamedArgsAction = makeStreamable(b.stream.TestMulticlassNamedArgs);

export const TestNamedArgsLiteralBoolAction = makeStreamable(b.stream.TestNamedArgsLiteralBool);

export const TestNamedArgsLiteralIntAction = makeStreamable(b.stream.TestNamedArgsLiteralInt);

export const TestNamedArgsLiteralStringAction = makeStreamable(b.stream.TestNamedArgsLiteralString);

export const TestOllamaAction = makeStreamable(b.stream.TestOllama);

export const TestOpenAILegacyProviderAction = makeStreamable(b.stream.TestOpenAILegacyProvider);

export const TestOpenAIShorthandAction = makeStreamable(b.stream.TestOpenAIShorthand);

export const TestRetryConstantAction = makeStreamable(b.stream.TestRetryConstant);

export const TestRetryExponentialAction = makeStreamable(b.stream.TestRetryExponential);

export const TestSingleFallbackClientAction = makeStreamable(b.stream.TestSingleFallbackClient);

export const TestVertexAction = makeStreamable(b.stream.TestVertex);

export const TestVertexWithSystemInstructionsAction = makeStreamable(b.stream.TestVertexWithSystemInstructions);

export const UnionTest_FunctionAction = makeStreamable(b.stream.UnionTest_Function);

export const UseBlockConstraintAction = makeStreamable(b.stream.UseBlockConstraint);

export const UseMalformedConstraintsAction = makeStreamable(b.stream.UseMalformedConstraints);

export const UseNestedBlockConstraintAction = makeStreamable(b.stream.UseNestedBlockConstraint);
