/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: do not edit it. Instead, edit the BAML
// files and re-generate this code.
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code
import type { BamlStream } from '@boundaryml/baml';
import type { RecursivePartialNull } from '../types';

/**
 * Type for representing a partial response with type safety
 * @template Output The type of the partial response data
 */
export type PartialResponse<Output> = {
  partial?: RecursivePartialNull<Output> | null
  final?: never
}

/**
 * Type for representing a final response with type safety
 * @template Output The type of the final response data
 */
export type FinalResponse<Output> = {
  partial?: never
  final: Output
}

/**
 * Configuration for streaming mode, which provides incremental updates.
 * Use this when you want to show partial results as they become available.
 *
 * @template Output Type of the incremental response chunks
 */
export type StreamingInputProps<Output> = {
  stream: true
  onPartial?: (response?: RecursivePartialNull<Output>) => void
  onFinal?: (response?: Output) => void
   /** Called if the operation fails */
  onError?: (error: Error) => void
}

/**
 * Options interface for non-streaming mode.
 * @template Output The type of the final response data
 */
export type NonStreamingInputProps<Output> = {
  stream?: false
  onPartial?: never
  onFinal?: (response?: Output) => void
   /** Called if the operation fails */
  onError?: (error: Error) => void
}

/**
 * Union type of all possible options.
 * @template Output The type of the response data
 */
export type UseLLMOptions<Output> = StreamingInputProps<Output> | NonStreamingInputProps<Output>

export type ServerAction<Input, Output> = {
  (input: Input, options: { stream: true }): Promise<ReadableStream<Uint8Array>>;
  (input: Input, options?: { stream?: false }): Promise<Output>;
  (input: Input, options?: { stream?: boolean }): Promise<Output | ReadableStream<Uint8Array>>;
};

export type BaseReturnType<Output> = {
   /**
   * The complete, final result of the operation.
   * Only available after successful completion (when isSuccess is true).
   * Null during loading or if an error occurred.
   */
   data?: Output;
   /**
    * Error details if the operation failed.
    * Check this when isError is true to handle the failure.
    */
   error: Error | null;
   /**
    * True if the operation failed.
    * Use this to conditionally render error states or retry options.
    */
   isError: boolean;
   /**
    * True while the operation is in progress.
    * Use this to show loading states, spinners, or disable controls.
    */
   isPending: boolean;
   /**
    * True if the operation completed successfully.
    * Check this before accessing the final data.
    */
   isSuccess: boolean;
   /**
    * The current phase of the operation:
    * - idle: Initial state, ready to start
    * - loading: Operation in progress
    * - success: Completed successfully
    * - error: Failed with an error
    */
   status: "idle" | "pending" | "success" | "error";
}

/**
 * Return type for streaming mode, extends base return type.
 */
export type StreamingReturnType<Output, Input extends unknown[]> = BaseReturnType<Output> & {
     /**
      * The most recent partial result from the stream.
      * Updates continuously while streaming, showing interim progress.
      * Use this to implement real-time UI updates, typing effects,
      * or progress indicators.
      */
     partialData?: RecursivePartialNull<Output> | null;

      /**
      * Call this function to start the operation.
      * Returns a promise that resolves with the final result or null if it failed.
      * If the last parameter of Input is the options object, it will be omitted.
      */
     mutate: Input extends [...infer Rest, { stream?: true }]
       ? (...args: Rest) => Promise<ReadableStream<Uint8Array>>
       : (...args: Input) => Promise<ReadableStream<Uint8Array>>;
};

/**
 * Return type for non-streaming mode, extends base return type.
 */
export type NonStreamingReturnType<Output, Input extends unknown[]> = BaseReturnType<Output> & {
   /** Not available in non-streaming mode */
   partialData?: never;
   mutate: Input extends [...infer Rest, { stream?: false }]
   ? (...args: Rest) => Promise<Output>
   : (...args: Input) => Promise<Output>;
};

/**
 * Conditional return type based on the options provided.
 */
export type UseLLMReturnType<Output, Input extends unknown[], TOptions extends UseLLMOptions<Output>> =
  TOptions extends { stream: true }
    ? StreamingReturnType<Output, Input>
    : NonStreamingReturnType<Output, Input>;