[package]
edition = "2021"
name = "baml-types"
version.workspace = true
authors.workspace = true
description.workspace = true
license-file.workspace = true

[lints.rust]
dead_code = "deny"
unused_imports = "deny"
unused_variables = "deny"

# Attention:
#   Please try to keep this crate low-dependency! We want to keep this as minimal as possible.
[dependencies]
anyhow.workspace = true
clap.workspace = true
derive_builder.workspace = true
log.workspace = true
minijinja.workspace = true
once_cell.workspace = true
serde.workspace = true
serde_json.workspace = true
strum.workspace = true
time.workspace = true
tracing-core.workspace = true
web-time.workspace = true

[dependencies.indexmap]
workspace = true
optional = true


[features]
default = ["stable_sort"]
stable_sort = ["indexmap"]
