[project]
name = "python-integ-tests"
version = "0.1.0"
description = ""
authors = [{ name = "None" }]
requires-python = "~=3.8"
readme = "README.md"
dependencies = [
    "assertpy",
    "maturin",
    "psutil",
    "pydantic",
    "pytest",
    "pytest-asyncio",
    "python-dotenv",
    "requests",
    "ruff",
]

[dependency-groups]
dev = ["types-assertpy"]
