name: Publish python

on:
  workflow_call: {}
  push:
    branches: [sam/py-release3]

concurrency:
  # suffix is important to prevent a concurrency deadlock with the calling workflow
  group: ${{ github.workflow }}-${{ github.ref }}-build-python
  cancel-in-progress: true

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.8"
      - uses: actions/download-artifact@v4
        with:
          pattern: wheels-*
          path: dist
          merge-multiple: true
          run-id: 12187401980
          github-token: ${{ secrets.SAM_GITHUB_PAT }}

      # Verify we have the expected number of wheels
      - name: Verify wheel count
        run: |
          set -euxo pipefail
          ls dist/
          wheel_count=$(ls dist/*.whl 2>/dev/null | wc -l)
          if [ "$wheel_count" -lt 5 ]; then
            echo "Error: Expected at least 5 wheels, but found $wheel_count"
            exit 1
          fi
          echo "Found $wheel_count wheels"

      # authz is managed via OIDC configured at https://pypi.org/manage/project/baml-py/settings/publishing/
      # it is pinned to this github actions filename, so renaming this file is not safe!!
      - name: Publish package to PyPI
        uses: PyO3/maturin-action@v1
        with:
          command: upload
          args: dist/*