name: Publish GitHub Release

on:
  workflow_call: {}
  push:
    branches: [sam/py-release3]

jobs:
  release-github:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get Changelog
        id: latest_release
        run: |
          echo "::set-output name=changelog::$(awk '/^## \[/{if (p) exit; p=1} p' CHANGELOG.md)"

      - uses: actions/download-artifact@v4
        with:
          path: gh-artifacts
          run-id: 12187401980
          github-token: ${{ secrets.SAM_GITHUB_PAT }}
      
      - run: ls -la gh-artifacts

      - name: Create Release
        if: false
        uses: mikepenz/action-gh-release@v1 #softprops/action-gh-release
        with:
          body: ${{steps.latest_release.outputs.changelog}}
          tag_name: "0.70.1"
          files: gh-artifacts/*
